### ISSUE TITLE
How long will it take to assign taxonomy for 18S V4 region?

### ISSUE THREAD

**Issue by zlei94** [benjjneb/dada2#926] opened 2020-01-23 11:12 UTC
I am currently evaluating a Illumina HiSeq(PE250) dataset targeting the V4 region of 18S rDNA for a total of 39 samples. After removing chimeras, 5697 out of 7651 sequences (the merged length varying from 220 bp to 400 bp with minOverlap=20 ) were obtained.  However, in the later taxonomic assignment, no output was obtained after running >15 hours. So I want to ask how long it will take to assign taxonomy targeting the V4 region of 18S rDNA for such a dataset? Or if something was wrong with the previous steps?

**Comment by benjjneb** [comment] 2020-01-23 13:33
It shouldn't be taking that long. Are you using the `multithread=TRUE` option?

Also, sometimes taxonomy assignment can take much longer than expected if memory is restricted, as it can lead to "swapping". If that might be the case for you (16GB is enough to assign against Silva easily, but 8GB or less could run into this issue) then I would recommend finding a higher memory compute resource for this step.

**Comment by zlei94** [comment] 2020-01-23 14:00
Thanks！My computer memory is 8GB, maybe that's why.

**Comment by pdcountway** [comment] 2020-02-03 13:44
Hi - I am having a similar issue with assigning taxonomy. In the past it has taken me ~60 hours to assign taxonomy to ~4000 ASVs using the PR2 18S reference database. I run (and am currently running ) this process on our supercomputer and typically assign the job 32 cores and 64 Gb of RAM. The current job is assigning taxonomy to a few thousand ASVs using the PR2 18S reference data and it has been running for 64+ hours. I specified multithread=32, but I assume that is basically the same as saying multitthread=TRUE, given that I specified the number of cores? I submit the jobs via a 'qsub' PBS command, and most of the time they start immediately. Any suggestions?
@kguay, @btupper

**Comment by pdcountway** [comment] 2020-02-03 18:08
> Hi - I am having a similar issue with assigning taxonomy. In the past it has taken me ~60 hours to assign taxonomy to ~4000 ASVs using the PR2 18S reference database. I run (and am currently running ) this process on our supercomputer and typically assign the job 32 cores and 64 Gb of RAM. The current job is assigning taxonomy to a few thousand ASVs using the PR2 18S reference data and it has been running for 64+ hours. I specified multithread=32, but I assume that is basically the same as saying multitthread=TRUE, given that I specified the number of cores? I submit the jobs via a 'qsub' PBS command, and most of the time they start immediately. Any suggestions?
> @kguay, @btupper

Update: We just checked the job I'm running and it is only running on a single thread, instead of the 32 that I specified in the R command. Any ideas?
This is the script I launched: > taxa <- assignTaxonomy(seqtab.nochim, refFasta = "/path_to_reference_database/pr2_version_4.12.0_18S_dada2.fasta", taxLevels = PR2_tax_levels, minBoot = 0, outputBootstraps = TRUE, verbose = TRUE, multithread =32)

**Comment by benjjneb** [comment] 2020-02-03 18:26
> Update: We just checked the job I'm running and it is only running on a single thread, instead of the 32 that I specified in the R command. Any ideas?

Most often this is an issue with the compute resources that are being allocated to your job, that is... it only has access to one core or one thread. Are you using something like SLURM to submit jobs to the supercomputer? You may need to check how to specify the resources you are requesting and make sure you are getting 32 threads, if that's how many you want.

**Comment by kguay** [comment] 2020-02-03 18:42
> Are you using something like SLURM to submit jobs to the supercomputer?

Yes, we are using PBS Pro and he is requesting and getting the 32 cores. The filter and trim step uses all cores, but not the learnErrors or taxonomy steps.

**Comment by pdcountway** [comment] 2020-02-04 13:25
Hi All,
It's unclear to me how we troubleshoot the non-use of assigned cores at specific steps in the dada2 process. Does this trace back to installation problems that we had a year ago? Wasn't there something related to RccParallel - but if so, why would the process call the assigned cores sometimes and not others? Who do we even ask about this - dada2 developers?, R-developers?, PBS Pro -developers? Thanks! @benjjneb @kguay @btupper Note: we're using the latest version of R (3.6.2) and dada2 (v1.14).

**Comment by benjjneb** [comment] 2020-02-05 15:49
> Yes, we are using PBS Pro and he is requesting and getting the 32 cores. The filter and trim step uses all cores, but not the learnErrors or taxonomy steps.

There is a clue here. The `filterAndTrim` command relies on a type of multithreading based on "forking" the R process. Each R process has just 1 thread, but a bunch of different processes are made.

The `learnErrors`, `dada` and `assignTaxonomy` commands use RcppParallel for multithreading. That is, there is no copying of the R process, but the RcppParallel backend requisitions and utilizes additional threads.

So... forking multithreading is working as expected, but the RcppParallel multithreading based on Intel TBB (Threading Building Blocks) is failing to access the 32 cores for some reason.

To me this suggests that the issue is either in the job submission system, which is somehow limiting  access to multithreading via TBB within an R process, or with RcppParallel on your particular architecture. But I don't know which it would be. Is it possible to ask a sysadmin on your supercomputer if they have any ideas, given the above observation?

**Comment by pdcountway** [comment] 2020-02-05 15:59
Hi @benjjneb , This is great. Thanks for the explanation of the different types and uses of multithreading in the dada2 process. @kguay mentioned above is our IT Director. We'll update when we learn anything new. @btupper
Cheers!

**Comment by pdcountway** [comment] 2020-02-11 17:32
> Hi @benjjneb , This is great. Thanks for the explanation of the different types and uses of multithreading in the dada2 process. @kguay mentioned above is our IT Director. We'll update when we learn anything new. @btupper
> Cheers!

Well, it seems to be running again and we can confirm that assignTaxonomy is in fact using 32 cores, as assigned via multithread = 32. All 32 cores are running at ~100%. The only difference with this session is that the current job was not submitted with PBS Pro, but launched directly into an interactive session.

**Comment by benjjneb** [comment] 2020-04-06 00:10
Closing, but please update if you ever nailed down what was going on w/ to the interaction between dada2 and PBS Pro here.

**Closed by benjjneb** 2020-04-06 00:10 UTC
