### ISSUE TITLE
questions about several parameters in setDadaOpt()

### ISSUE THREAD

**Issue by yhuang15** [benjjneb/dada2#480] opened 2018-06-01 15:32 UTC
I need help understanding several parameters set by setDadaOpt():

1. What is the difference between MIN_FOLD and MIN_ABUNDANCE?  

2. If we set MIN_ABUNDANCE to a certain value, does it take precedence before MIN_HAMMING?  For example, if we set MIN_ABUNDANCE = 2 and there is a sequence satisfying MIN_HAMMING by a good margin but its abundance is 1, what would happen?

**Comment by benjjneb** [comment] 2018-06-01 15:40
> What is the difference between MIN_FOLD and MIN_ABUNDANCE?

If the error model predicts that X reads of some sequence would be produced by amplicon sequencing, then there must be at least MIN_FOLD * X reads of that sequence for it to be inferred as a biological variant. This condition is enforced in addition to the normal P < OMEGA_A condition.

> If we set MIN_ABUNDANCE to a certain value, does it take precedence before MIN_HAMMING? 

They are both enforced at the same time. It's an AND relationship between those two conditions.

**Comment by yhuang15** [comment] 2018-06-01 16:06
That means if we believe sequences with big Hamming distance are very unlikely to result from PCR error, we should never set MIN_ABUNDANCE to be greater than 1, otherwise we might lose true ASVs that are very rare, correct?  On a related question - for sequences that do not satisfy the parameters to form new partitions, are they discarded or being "corrected"?  I noticed that number of denoised reads are usually slightly smaller than dereplicated reads.  Does that mean some reads are thrown away?

**Comment by benjjneb** [comment] 2018-06-01 16:15
> That means if we believe sequences with big Hamming distance are very unlikely to result from PCR error, we should never set MIN_ABUNDANCE to be greater than 1, otherwise we might lose true ASVs that are very rare, correct? 

Pretty much. The main use for `MIN_ABUNDANCE` is to reduce computation time in large pooled datasets, otherwise I wouldn't recommend changing it.

> On a related question - for sequences that do not satisfy the parameters to form new partitions, are they discarded or being "corrected"?

Most are corrected, but some that are not if they are deemed to unlikely to have been produced by the partition they are assigned to. See `OMEGA_C` in ?setDadaOpt. This almost exclusively affects singletons, as singletons cannot form their own partitions. That is the cause of why denoised read number is slightly smaller than the input reads.

**Comment by yhuang15** [comment] 2018-06-01 16:43
@benjjneb Thanks!  This is very helpful to me.  And thanks for creating a great tool!

**Closed** 2018-06-06 20:57 UTC
