### ISSUE TITLE
Most of my ITS ASV's  map to Other (>60%)

### ISSUE THREAD

**Issue by hereformore** [benjjneb/dada2#1768] opened 2023-06-28 21:21 UTC
I did ITS sequencing of stool samples for Fungi. However when I look at relative abundances, even for phylum 60-70% of my relative abundance graph is Other DNA. 

When I look at how my ASVs map with taxa from Unite Database, the majority of taxa do not map past Kingdom (only 27% of Phylum maps to a reference sequence, besides Kingdom:Fungi). 

Is this normal? And is there anything I can do to filter the data so it's not just 90% other? 

This is what was done already by a collaborator (Dada 1.16)

-  Amplicon sequence variants (ASVs): paired FASTQ reads were trimmed, and then filtered to remove reads containing Ns, or with maximum expected errors >=2. 
-  Samples with fewer than 1,000 sequences were discarded. ASVs accounting for less than one millionth of all strain-level markers were discarded

**Comment by benjjneb** [comment] 2023-06-28 21:50
Try `assignTaxonomy(..., tryRC=TRUE)` to see if the cause might be variable ordination of your reads (this option will cause the reverse-complement of each sequence to be compared against the reference database as well).

If that doesn't change things, I would start BLAST-ing some of your more abundant non-classified ASVs against a broad database like nt. What are they? Off-target amplification is another possibility that should show up with this approach.

**Comment by hereformore** [comment] 2023-06-28 22:48
thank you so much. 

I set tryRC=TRUE originally and came up with the same result. 

I also looked up the top non-classifed ASVs and they tracked to "uncultured fungi", also results for plant DNA (solanium = tomato, another blast was for spinach).

![image](https://github.com/benjjneb/dada2/assets/137748676/8cffc79b-143d-4820-a04f-56f1576e2575)
[fungiexport.xlsx](https://github.com/benjjneb/dada2/files/11900475/fungiexport.xlsx)

If it is off target amplification or even BLASTIng does not yield a specific genus/phylum, is there any acceptable option to filtering these ASVs? Or do i leave them as is and deal with the enormous amount of other.

**Comment by benjjneb** [comment] 2023-06-28 23:08
Interpreting results from BLAST against nt can be a bit complicated, because not everything is correctly labelled. Are you sequencing tomato-related samples?

If so, the fact that tomato is showing up in your non-classifying ASVs (even if its not the only hit) would be highly suggestive of substantial off-target amplification.

If my presumptions so far are true, then there are at least two possible paths forward. One: Screen all ASVs against the tomato genome and remove anything that hits (this would be done outside DADA2, see previous work but this is very commonly done in human microbiome studies), and/or Two: Subset your analysis down to only those ASVs that classify as some kind of fungi.

On that second point -- this is a valid approach. Every sequencing-based method is already subsetting down to some fraction of what is really there. As long as your are clear and open about how you do further subsetting, it is valid.

**Comment by hereformore** [comment] 2023-06-29 00:21
Thank you! 

These are stool samples from human patients. So just the first sample was tomato related, the second highest un-classified ASV was Spinach, then Sunflower, then Spinach, then a bacteria. To be clear the first result on blast was "uncultured fungus" then the next 5+ would be the tomato/spinach/sunflower species as shown below. 

i can definitely go through each of the highest  count unclassified ASVs that match an uncultured fungi by kingdom, but no phylum. And on blast match uncultured fungus + Tomato or Spinach etc and remove them. Is that what you mean by the second point?


![image](https://github.com/benjjneb/dada2/assets/137748676/9e6caceb-2b35-489e-8ca5-df9394306e6e)
![image](https://github.com/benjjneb/dada2/assets/137748676/8b26fe29-e7cc-4256-8334-df518e65f7c8)

![image](https://github.com/benjjneb/dada2/assets/137748676/50f6b83f-3278-4b16-9696-7ac49e5f2e6d)

**Comment by gzahn** [comment] 2023-08-12 22:52
https://www.tandfonline.com/doi/abs/10.1080/00275514.2023.2206931?journalCode=umyc20

We found that the standard fungal ITS primers co-amplify lots of eukaryotes (~40% of the "fungi" in the studies we examined weren't actually fungi!), and you really do just have to live with that and remove them downstream. If you used the UNITE_Fungi database to assign taxonomy, it would lead to a lot of "unknown fungus" assignments that were actually tomato or whatever. Using the UNITE_All database will help place these into the correct kingdom and then you can remove them downstream.

**Comment by LukeLikesDirt** [comment] 2023-09-19 00:12
I would suggest extracting the ITS region using [ITSxpress](https://github.com/USDA-ARS-GBRU/itsxpress) prior to quality filtering and denoising in DADA2. I also suggest doing this to the UNITE database using [ITSx](https://microbiology.se/software/itsx/) prior to the taxonomic assignment ([example here](https://github.com/LukeLikesDirt/MycorrhizasAustralianForests/blob/main/code/01.Bioinformatics_ITS/05.Prepare_UNITE.sh)). In my experience this increases the number of OTUs assigned to the level genus: (1) because extracting the ITS region in your reads removes a short fragment from either 18S, 5.8S or 28S which has no species resolution and random errors in this region could complicate taxonomic assignment, and (2) because extracting the ITS region from UNITE will increase sequence coverage between representative and reference sequence which should improve taxonomic assignment estimations. 

I recommend using the [UNITE all eukaryotes](https://dx.doi.org/10.15156/BIO/2938069) reference dataset and extract the ITS using '-t All' in ITSx, and also use the options '--region ALL' on your data in ITSxpress. This will allow you to gauge how many of your sequences belong to non-fungal eukaryotes.

**Closed** 2024-05-27 21:08 UTC
