### ISSUE TITLE
Regarding Biocgeneric download

### ISSUE THREAD

**Issue by Ruddhida** [benjjneb/dada2#1296] opened 2021-03-11 04:50 UTC
Hello, I know I have sent lots of queries as I do not have any technical background and have no one whom I can take the help of. So, please take up my request.
If you check this link **https://bioconductor.org/packages/release/bioc/html/BiocGenerics.html** it's written as 0.36.0 version but while downloading, the 0.34.0 version is getting downloaded. 

Thank you
Ruddhida

**Comment by benjjneb** [comment] 2021-03-11 20:52
Duplicate of #1294

**Closed by benjjneb** 2021-03-11 20:52 UTC
