### ISSUE TITLE
Error with mergePairs: subscript out of bounds

### ISSUE THREAD

**Issue by as703** [benjjneb/dada2#547] opened 2018-08-20 16:37 UTC
Hi,

I'd be very grateful for some assistance. I'm using dada2 ver 1.8 and following the guide available here: https://f1000research.com/articles/5-1492/v2 

I'm following every step exactly and using the reference dataset but keep running into an error when tring to run mergePairs.

It is set to verbose and appears to be working fine (performs the merger on about 50-60 samples) until it throws an error: Error in outs[, 1] : subscript out of bounds. It doesn't tell me the name of the sample that this error occurs at.

From reading around, I wonder if this related to the Trim and Filter step but my code is identical to the example and the step seems to run fine:

for(i in seq_along(fnFs)) {
  fastqPairedFilter(c(fnFs[[i]], fnRs[[i]]),
                    c(filtFs[[i]], filtRs[[i]]),
                    trimLeft=10, truncLen=c(245, 160),
                    maxN=0, maxEE=2, truncQ=2,
                    compress=TRUE, verbose=TRUE)
}

I'm unsure how to go about debugging this error and would be grateful for any suggestions.

Many thanks in advacne for your help.

Best wishes,

Alasdair

**Comment by benjjneb** [comment] 2018-08-20 20:42
I believe this is caused by a bug handling the case of zero merged reads, and that the fix we have in the current version of the package will solve your problem.

Can you try installing the current devel version and seeing it that fixes this?

```
library(devtools)
devtools::install_github("benjjneb/dada2")
# Continue at point throwing an error
```

**Comment by as703** [comment] 2018-08-20 20:57
Yes!

That fixed it.

Many thanks.

**Closed** 2018-08-20 20:59 UTC
