### ISSUE TITLE
Non-corresponding maps and dada-outputs

### ISSUE THREAD

**Issue by shandley** [benjjneb/dada2#135] opened 2016-10-11 15:01 UTC
Ran into this error message today following a workflow I have used for several other projects.

Here is the command:

```
mergers <- mergePairs(dadaFs, derepFs, dadaRs, derepRs, verbose=TRUE)
Error in mergePairs(dadaFs, derepFs, dadaRs, derepRs, verbose = TRUE) : 
  Non-corresponding maps and dada-outputs.
```

This is what derepFS and derepRS look like, so I am pretty sure everything up through the dereliction worked.

> derepFs[1]
> $NA0000418658
> derep-class: R object describing dereplicated sequencing reads
> $uniques: 76330 reads in 10310 unique sequences
>   Sequence lengths: min=215, median=215, max=215
> $quals: Quality matrix dimension:  10310 215
>   Consensus quality scores: min=12, median=38, max=40
> $map: Map from reads to unique sequences:  1 10 4 699 2 ...
> 
> derepRs[1]
> $NA0000418658
> derep-class: R object describing dereplicated sequencing reads
> $uniques: 76330 reads in 14957 unique sequences
>   Sequence lengths: min=215, median=215, max=215
> $quals: Quality matrix dimension:  14957 215
>   Consensus quality scores: min=12, median=37.5, max=40
> $map: Map from reads to unique sequences:  1 12360 4 816 2 ...

I checked the code for mergePairs and it looks like I must have an issue with the $map value having an NA somewhere. Any advice on how to move forward without having to rerun sample inference?

Thanks!

Scott

**Comment by benjjneb** [comment] 2016-10-11 16:58
Hi Scott,
Can you check if the length of the fastq inputs to derepFs and derepRs were the same?

```S
length(derepFs[[1]]$map)
length(derepRs[[1]]$map)
```

My guess is that the starting fastqs weren't in matched order as expected by mergePairs. This can happen if the forward and reverse files were filtered independently.

**Comment by shandley** [comment] 2016-10-11 18:36
Hi Ben,

Here are the results from the length commands

```
> length(derepFs[[1]]$map)
[1] 76330
> length(derepRs[[1]]$map)
[1] 76330
```
 and here is the command I used to filter:

```{r}
# Make directory and filenames for the filtered fastqs
filt_path <- file.path(path, "filtered")
if(!file_test("-d", filt_path)) dir.create(filt_path)
filtFs <- file.path(filt_path, paste0(sample.names, "_F_filt.fastq.gz"))
filtFs
filtRs <- file.path(filt_path, paste0(sample.names, "_R_filt.fastq.gz"))
filtRs
# Filter
for(i in seq_along(fnFs)) {
  fastqPairedFilter(c(fnFs[i], fnRs[i]), c(filtFs[i], filtRs[i]),
                    trimLeft=c(10, 10), truncLen=c(225,225), 
                    maxN=0, maxEE=2, truncQ=2, 
                    compress=TRUE, verbose=TRUE)
}

```

The input fastq's were sorted ahead of time and split using qiime and turning off the qc settings so they were not trimmed, just split. Can confirm that neither R1 nor R2 was cleaned by QIIME and all input sequences are 250 bases in length with equal pairs.

Here is the full markdown I am running. Goes up through sequence inference in case you are curious.

```{r}
# Set file paths
path <- "~/Desktop/"

fns <- sort(list.files(path))
fns
fnFs <- fns[grepl("R1", fns)]
fnFs
fnRs <- fns[grepl("R2", fns)]
fnRs

```

```{r}
# View sequence quality
fastqs <- fns[grepl(".fastq$", fns)]
fastqs
fastqs <- sort(fastqs) # Sort ensures forward/reverse reads are in same order
fastqs
fnFs <- fastqs[grepl("_R1", fastqs)] # Just the forward read files
fnFs
fnRs <- fastqs[grepl("_R2", fastqs)] # Just the reverse read files
fnRs

# Get sample names from the first part of the forward read filenames
sample.names <- sapply(strsplit(fnFs, "_"), `[`, 1)
sample.names

# Fully specify the path for the fnFs and fnRs
fnFs <- file.path(path, fnFs)
fnRs <- file.path(path, fnRs)

# Sequence quality plots
plotQualityProfile(fnFs[1]) + ggtitle("Fwd")
plotQualityProfile(fnRs[1]) + ggtitle("Rev")

```

```{r}
# Make directory and filenames for the filtered fastqs
filt_path <- file.path(path, "filtered")
if(!file_test("-d", filt_path)) dir.create(filt_path)
filtFs <- file.path(filt_path, paste0(sample.names, "_F_filt.fastq.gz"))
filtFs
filtRs <- file.path(filt_path, paste0(sample.names, "_R_filt.fastq.gz"))
filtRs
# Filter
for(i in seq_along(fnFs)) {
  fastqPairedFilter(c(fnFs[i], fnRs[i]), c(filtFs[i], filtRs[i]),
                    trimLeft=c(10, 10), truncLen=c(225,225), 
                    maxN=0, maxEE=2, truncQ=2, 
                    compress=TRUE, verbose=TRUE)
}

```

```{r}
# Dereplicate sequences
derepFs <- derepFastq(filtFs, verbose=TRUE)
derepRs <- derepFastq(filtRs, verbose=TRUE)
# Name the derep-class objects by the sample names
names(derepFs) <- sample.names
names(derepRs) <- sample.names

# Now is a good time to save your environment

```

```{r}
# Sequence inference
ddF <- dada(derepFs[1:40], err=NULL, selfConsist = TRUE, multithread = TRUE)
ddR <- dada(derepRs[1:40], err=NULL, selfConsist = TRUE, multithread = TRUE)

plotErrors(ddF)
plotErrors(ddR)

# Pooled sequence inference based on error estimates in ddF and ddR
dadaFs <- dada(derepFs, err=ddF[[1]]$err_out, pool = TRUE)
dadaRs <- dada(derepFs, err=ddR[[1]]$err_out, pool = TRUE)

plotErrors(dadaFs, nominalQ = TRUE) + ggtitle("Forward")
plotErrors(dadaRs, nominalQ = TRUE) + ggtitle("Reverse")

```

**Comment by benjjneb** [comment] 2016-10-12 04:13
I don't catch anything unusual looking through that.

I think I need to be able to reproduce this on my end. Can you check if mergePairs fails on just the first sample, and then share the R objects from that sample?

```S
mergePairs(dadaFs[[1]], derepFs[[1]], dadaRs[[1]], derepRs[[1]], verbose=TRUE)
# Assuming that fails
saveRDS(dadaFs[[1]], "ddF.rds")
saveRDS(derepFs[[1]], "drpF.rds")
saveRDS(dadaRs[[1]], "ddR.rds")
saveRDS(derepRs[[1]], "drpR.rds")
```

Also, what version of the package/R do you have?

```S
R.version
packageVersion("dada2")
```

**Comment by benjjneb** [comment] 2016-10-31 20:48
Closing under the assumption this was solved, but please re-open if things still aren't working.

**Closed by benjjneb** 2016-10-31 20:48 UTC

**Comment by dario196** [comment] 2018-09-26 00:07
Hi Ben, I having a similar problem. I am running mergesPairs and get te same error. I check the files from filterAndTrim, and they have the same number of reads and IDs. I used matchIDs=TRUE. 

filt_trim <- filterAndTrim(fwd=file.path(pathF, fastqFs), filt=file.path(filtpathF, fastqFs),
	rev=file.path(pathR, fastqRs), filt.rev=file.path(filtpathR, fastqRs), 
	truncLen=c(240,200), maxEE=2, truncQ=11, maxN=0, rm.phix=TRUE,
	compress=TRUE, verbose=TRUE, multithread=TRUE, matchIDs=TRUE)
Then I did dereplication and dada:

derepF <- derepFastq(filtFs)
    ddF <- dada(derepF, err=NULL, USE_QUALS=FALSE, selfConsist=TRUE, multithread=TRUE) #USE_QUALS=FALSE, transition rates are estimated by maximum likelihood
    derepR <- derepFastq(filtRs)
    ddR <- dada(derepF, err=NULL, USE_QUALS=FALSE, selfConsist=TRUE, multithread=TRUE) #USE_QUALS=FALSE, transition rates are estimated by maximum likelihood

Eveything works OK. But then:

merger <- mergePairs(ddF, derepF, ddR, derepR)

Error in mergePairs(ddF, derepF, ddR, derepR) :
  Non-corresponding maps and dada-outputs.

Then I check:

> length(derepF$map)
[1] 340975
> length(derepR$map)
[1] 340975
> length(ddR$map)
[1] 340271
> length(ddF$map)
[1] 340271

Everything looks OK. But, I don't know if all the lengths should be the same or only between pairs?

Finally:

> R.version
               _
platform       x86_64-pc-linux-gnu
arch           x86_64
os             linux-gnu
system         x86_64, linux-gnu
status
major          3
minor          5.0
year           2018
month          04
day            23
svn rev        74626
language       R
version.string R version 3.5.0 (2018-04-23)
nickname       Joy in Playing
> packageVersion("dada2")
[1] ‘1.8.0’

I don't know what is wrong. Thanks for all your help.

Dario X.

**Comment by benjjneb** [comment] 2018-09-26 00:12
> ddR <- dada(derepF, err=NULL, USE_QUALS=FALSE, selfConsist=TRUE, multithread=TRUE) 

There may be some typos (see above) in your F/R specifications. I would double/triple check those (I know I mess these up sometimes) and see if that fixes the problem.

**Comment by dario196** [comment] 2018-09-26 00:28
Thank you it works. I been looking to that code all day. 
Now the problem is that I get 0 sequences from mergePairs. I will change the parameters in filterAndTrim, and start again.

DX

**Comment by benjjneb** [comment] 2019-05-08 15:02
@mwcoulson 
> I chose to filter F & R reads separately as my F reads have a low quality score for the first 20 bases and so applied a left trim to them, while the reverse reads started off fine.

This is the problem, as this results in mismatched forward and reverse read files because some forward reads were kept that weren't kept in the reverse reads and vice versa. You need to filter the reads as pairs, which maintains the consistency between them. That's easy to do though by utilizing the 2-fold filtering arguments for paired reads.

```
out <- filterAndTrim(fnFs, filtFs, fnRs, filtRs, truncLen=c(275,225), trimLeft=c(20,0), 
maxN=0, maxEE=c(2,5), truncQ=2, rm.phix=TRUE,
compress=TRUE, multithread=4)
```

For example, `trimLeft=c(20, 0)` means trim the first 20 nts of the forward reads, and trim the first 0 reads (no trimming) of the reverse reads.

**Comment by zacklah** [comment] 2021-03-06 04:18
Hi Ben,
I am new in this field and experiencing the same problem. I run the same script in tutorial DADA2 for 16S, I reach this line:

**#Merging reads
mergers <- mergePairs(dadaFs, derepFs, dadaRs, derepRs, verbose=TRUE)**

and it gives this error: 

**Error in FUN(X[[i]], ...) : 
  Non-corresponding derep-class and dada-class objects.**

When I click on Show Traceback, this is what appear:

**Error in FUN(X[[i]], ...) : Non-corresponding derep-class and dada-class objects.
4.
stop("Non-corresponding derep-class and dada-class objects.")
3.
FUN(X[[i]], ...)
2.
lapply(seq_along(dadaF), function(i) { mapF <- getDerep(derepF[[i]])$map mapR <- getDerep(derepR[[i]])$map if (!(is.integer(mapF) && is.integer(mapR))) ...
1.
mergePairs(dadaFs, derepFs, dadaRs, derepRs, verbose = TRUE)**

Could you please help me on that? Thank in advance

**Comment by kblogan23** [comment] 2023-12-16 21:02
I am having a similar issue.
> dadaFs <- dada(derepFs, err=ddF[[1]]$err_out, pool=TRUE)
> dadaRs <- dada(derepRs, err=ddR[[1]]$err_out, pool=TRUE)
> mergers <- mergePairs(dadaFs, derepFs, dadaRs, derepRs)
Error: object 'dadaFs' not found

**Comment by benjjneb** [comment] 2024-01-04 04:37
@kblogan23 

Probably you called that `mergePairs` function in an environment that did not have `dadaFs` in it. I would check your prior R script, or perhaps what you are loading into the R environment if you have things broken up into pieces.
