### ISSUE TITLE
working with big data of paired end readings

### ISSUE THREAD

**Issue by yh330** [benjjneb/dada2#139] opened 2016-10-18 16:10 UTC
Hi, 
I am pretty new to dada2. and I've already liked very much ;)
I have gone through the tutorial, and want to use dada2 for my own data now. I have 216 samples in total, each with paired end readings. So I'm wondering the workflow for this. 

I sort of make a work flow by combining the "walk through" and "big data" together. 
1. I will put all the samples forward and reverse reading together in one folder. 
2. get all forward reading into fnFs and all reverse to fnRs
3. quality profile for each reading
4. filtering, I mainly follow the big data tutorial here, but I did forward and reverse separately. 
5. sampel inference, the same here, by using the filtered readings, I will do sample reference separately for forward and reverse readings. 
6. merge the forward and reverse reading together after sample inference (here i follow the walkthrough tutorial)
7. after merging, i will construct the sequence table and remove chimeras.
8. assign taxonomy

Sorry if this question here is too basic, just want to make sure I do things right here. 
And after we get the sequence table, I guess I will treat it as the usual OTU table, which I could assign some "random" name for each sequence, and use that for the following analysis?

Thanks a lot

**Comment by benjjneb** [comment] 2016-10-18 16:31
One crucial point, if doing a paired-end analysis, you need to use the `fastqPairedFilter` method for filtering. If you use `fastqFilter` separately on F and R, the resulting filtered files won't match each other and, later, merging will fail.

Minor points. It is generally sufficient to look at just a few samples to choose filtering/trimming parameters (assuming samples are from same run). And while it is fine to rename the sequence variants for readability, we strongly recommend retaining and reporting the default names -- the sequences themselves -- in some way, as those sequences are comparable to other results/data in a way that "OTU42" is not (eg. you can BLAST the sequence and get useful information out).

**Comment by yh330** [comment] 2016-10-19 09:43
thanks for the hints! can't wait to try it on our miseq run!!!!

**Comment by yh330** [comment] 2016-10-21 14:31
Hi,
I am trying my sequences (only three samples for testing) now, with the walkthrough and big data. The walkthrough steps works pretty well. but when I tried the big data work flow, after the sample inference, I want to merge forward and reverse together using mergers <- mergePairs( dds_forw, derep_forw, dds_rever, derep_rever, verbose=TRUE), it gave the error message that Error in mergePairs(dds_forw, derep_forw, dds_rever, derep_rever, verbose = TRUE) : 
  The dadaF/derepF/dadaR/derepR arguments must be the same length.

I am wondering what could be the reason for this, and how should I fix it?
Thanks a lot!

**Comment by benjjneb** [comment] 2016-10-21 14:36
Did you replace the `fastqFilter` step in the big data workflow with `fastqPairedFilter`? If not, that's the problem.

For paired-end reads, you have to use `fastqPairedFilter` in order for merging to work.

**Comment by yh330** [comment] 2016-10-21 14:39
yes, I used the pairedfiltered
for(i in seq_along(fnFs)) {
  fastqPairedFilter(c(fnFs[i], fnRs[i]), c(filtFs[i], filtRs[i]),
                    trimLeft=c(10, 10), truncLen=c(240,160), 
                    maxN=0, maxEE=2, truncQ=2, 
                    compress=TRUE, verbose=TRUE)
}

I did not change any parameters here though

**Comment by benjjneb** [comment] 2016-10-21 14:44
Hm. What is the output of the following?

```
length(dds_forw)
length(derep_forw)
length(dds_rever)
length(derep_rever)
```

**Comment by yh330** [comment] 2016-10-21 15:00
I found a typing error before, and changed it and re-run the sample inferences, then do merge, but still gave the same error. the length of them are all 3.

> length(dds_forw)
[1] 3
> length(derep_forw)
[1] 3
> length(dds_rever)
[1] 3
> length(derep_rever)
[1] 3

**Comment by benjjneb** [comment] 2016-10-21 17:09
The easiest way to diagnose the issue is if you can share the objects.

`saveRDS(dds_forw, "dds_forw.rds")` for each of those 4 objects, and then you can either email the rds files to me if small enough, or share another way if larger (eg. dropbox).

My email is benjamin DOT j DOT callahan AT gmail DOT com

**Comment by benjjneb** [comment] 2016-10-21 21:32
The dds_forw and dds_rever are correct, they are lists of three dada-class objects from your three samples.

The derep_forw and derep_rever are not correct, they are a single derep-class object from one sample. (By an unfortunate coincidence, a naked derep-class object has a length of three, matching the number of samples you are processing, so it wasn't obvious from just looking at the lengths).

This is probably due to how you combined the big data workflow, which loops over samples individually, and the tutorial workflow, which processes the samples all at once in a vectorized fashion.

I can see this being a common enough issue that I'm going to put together a paired-end version of the big data workflow.

**Comment by yh330** [comment] 2016-10-22 10:27
That will be awesome!! looking forward!

**Comment by yh330** [comment] 2016-10-22 10:30
That will be awesome! looking forward to it!

**Comment by benjjneb** [comment] 2016-10-24 21:22
The paired-end version of the big data workflow is now available: http://benjjneb.github.io/dada2/bigdata_paired.html

**Comment by benjjneb** [comment] 2016-10-24 21:22
Closing for now, but please re-open if this doesn't solve the problem.

**Closed by benjjneb** 2016-10-24 21:22 UTC

**Comment by annidjurhuus** [comment] 2017-11-08 17:33
Hi, 

I am using dada2 for a dataset from a MiSeq run (~700,000 reads). At first, I could not get the learnErrors function to work because it never converged with the entire dataset. I tried it on a subset of samples and the whole workflow worked just fine, which makes me think the workflow should also work for my entire dataset. However, my suspicion was that the data was too large so I tried the paired-end big data workflow. 

I understand from the string above that the fastqPairedFilter should be used on the paired-end workflow but don't understand why this function is not used in the example workflow from the link above?

I would not be surprised if my data has N's in it, but the strange thing is that if I run the filterAndTrim function, as given in the link above, on a folder with only one sample (doesn't matter which one) the workflow works but as soon as I add two samples it doesn't. I ran the exact code on the big data workflow given in the link above with the following error:

Error in dada(drps, err = NULL, selfConsist = TRUE, multithread = multithread) : 
  Invalid derep$uniques vector. Names must be sequences made up only of A/C/G/T.

I guess my question is: What could be the reasons it doesn't work to get the data to converge with the "not big data" workflow and why does filterAndTrim not run on more than one sample at a time with the big data workflow? 

Cheers, 
Anni

**Comment by benjjneb** [comment] 2017-11-09 01:06
Hi Anni,
I think your post is missing a link, so I'm guessing, but I think you are looking at this workflow? http://benjjneb.github.io/dada2/bigdata_paired.html

But in that case I'm confused, since it does use `filterAndTrim`. Possibly you were looking at an old version? In any case, please clarify.

As for `learnErrors` converging (or not) it almost never really matters if it perfeclty converges, as long as it gets close. The point is to get a good estimate of the errors for your data, convergence is just a convenient stopping point that usually is arrived at pretty quickly. See more here: http://benjjneb.github.io/dada2/faq.html#what-if-the-self-consistency-loop-terminated-before-convergence

**Comment by annidjurhuus** [comment] 2017-11-10 16:35
Thank you very much Ben! 

I was indeed talking about the link you provided. As I understood from the discussion above it seems to me that you are saying that when running the big data workflow for paired-end reads one should use the fastqPairedFilter function for filtering. However, in the workflow (http://benjjneb.github.io/dada2/bigdata_paired.html) you use the filterAndTrim function. This was not that important, just an observation that made me a little confused while going through the code. Especially since the big data workflow worked on individual samples but not on the whole dataset. 

Anyway, I changed the learnErrors to MAX_CONVERGENCE=20 and it works just fine (converges after 19). For future work, I would like to get the big data workflow to run on my computer though, do you have any ideas on why it would work on a single sample and not a batch?

I very much appreciate your help! Thank you. 
Anni

**Comment by benjjneb** [comment] 2017-11-10 18:32
Ah, if the confusion is just about `fastqPairedFilter` or `filterAndTrim`, they are functionally identical. In fact `filterAndTrim` calls `fastqPairedFilter` to do the actual filtering.

`filterAndTrim` is just a newer function introduced since the previous comments in this thread that handles multithreading, and is syntactically easier to use on multiple files (i.e. no loop required). But it's just a convenience thing.

As for the convergence thing: The algorithm is almost certainly "working" both the single sample and the batch, its just not converging as quickly on one of them. But as I mentioned above, that almost never matters in any case I've seen -- as long as it is getting close to convergence that is good enough.
