### ISSUE TITLE
Merging sequence tables generated using different mergePairs parameters

### ISSUE THREAD

**Issue by naurasd** [benjjneb/dada2#1244] opened 2021-01-11 10:06 UTC
Hi @benjjneb,

I am using dada2 for ASV inference of an ITS amplicon dataset. Reads were generated during various sequencing events. The same primers were used to amplify the target region. Performing all the steps down to forward/reverse read merging separately for each sequencing run and am merging sequence tables prior to chimera removal. I have been following the dada2 ITS tutorial, not truncating reads during the filterAndTrim step given the length variability of the ITS region. 

Here my question: I lost a lot of reads for one of my sequencing datasets during the read merging step, so I changed the mergePairs default values to minOverlap = 10 and maxMismatch = 1. However, for all of my other read sets, I kept the default values of minOverlap = 12 and maxMismatch = 0. Is that an issue for further downstream analysis when merging sequence tables that have been generated using different mergePairs parameters? May this be considered as bad analytical practice?

Thanks
Nauras

**Comment by benjjneb** [comment] 2021-01-11 21:11
Duplicate of #1245

**Closed by benjjneb** 2021-01-11 21:11 UTC

**Comment by naurasd** [comment] 2021-01-11 22:36
Sorry, but my other issue was about the truncLen parameter. So does this mean varying minOverlap and maxMismatch values prior to merging sequence tables is not an analytical issue?

**Comment by benjjneb** [comment] 2021-01-12 00:39
> So does this mean varying minOverlap and maxMismatch values prior to merging sequence tables is not an analytical issue?

In theory no. In all of this, one should be aware that these choices could affect how certain very short of very long ITS amplicons merge (or not) so a systematic effect in certain amplicon length classes is possible.

**Comment by naurasd** [comment] 2021-01-12 14:58
alright, thanks so much as always for the quick reply.
