### ISSUE TITLE
Taxonomic Assignment

### ISSUE THREAD

**Issue by katietogher** [benjjneb/dada2#849] opened 2019-10-06 11:48 UTC
Hi, 
I am currently running 16S through the dada2 pipeline. 
I have adjusted the filtering parameters a number of times to try and correct, am happy with the error rate and merging, however the entire samples appear to be primarily assigning to Proteoacteria (mitochondria) no matter what I adjust.

Any idea what might be happening. 
These are mixed stool/mucosal samples.

**Comment by benjjneb** [comment] 2019-10-06 18:58
I would try `assignTaxonomy(..., tryRC=TRUE)`, that will also test the reverse complement orientation of each ASV, and use that for assignment if it is closer to the reference database.

If that doesn't change things, I'd BLAST a few of the ASV sequences to double-check that they really appear to be mitochondrial DNA.

**Comment by katietogher** [comment] 2019-10-11 17:54
Thank you. 
I have tried this and still do not get proper assigments. 
Also the seqs are not hitting anything on BLAST.
I think it may be possible my files still have barcodes and/or adapters on them. Is there a function to remove these on dada2?

**Comment by benjjneb** [comment] 2019-10-11 17:57
> the seqs are not hitting anything on BLAST.

They are literally hitting nothing? Even if they have barcodes/adapters on them, the rest of the sequence should still be hitting something on BLAST.

If that's the case, then this is just just bad sequencing data, not something that bioinformatically fixable. You would need to generate new data.

**Comment by benjjneb** [comment] 2019-10-16 18:56
Closing under the assumption the issue is bad sequencing data. Feel free to reopen if there is additional pertinent information.

**Closed by benjjneb** 2019-10-16 18:56 UTC
