### ISSUE TITLE
Is using dada2 on PacBio SMRT Cell data feasible? 

### ISSUE THREAD

**Issue by JacobRPrice** [benjjneb/dada2#374] opened 2017-11-28 13:19 UTC
Hi everyone,

Our lab is interested in comparing/contrasting results from Illumina (MiSeq) and PacBio SMRT Cell sequencing; 16s amplicons were sequenced for both runs (i.e. no metagenomics, just amplicon data). I want the analysis pipelines to be as similar as possible between the two sequencing technologies. I know that you guys have expanded dada2 support to include the use of 454/Pyrosequencing results ( #29 ), but I haven't been able to find any information regarding whether dada2 is suitable for use on PacBio SMRT Cell data. 

My concerns boil down to two questions:    
1) Given the differences between PacBio and Illumina (and 454) technologies, does it "make sense" to utilize dada2 to carry out ASV identification? Specifically (and loosely speaking), PacBio makes multiple passes over the same template strand within each zero mode waveguide (ZMW) and builds a consensus sequence for that template after the run taking the read and read quality into account, while Illumina technologies observe read identity on a cluster of identical templates. From a statistical perspective, I think the two are different approaches to the same problem and I'm unsure if the treatment of one is appropriate for the other. 
2) If so, is it possible to use dada2 in it's current state?

Thank you for any insight you'd be able to provide, 
Jake

**Comment by benjjneb** [comment] 2017-11-29 16:41
Possible? Yes. How well would it work? I'm not sure, but would be very interested to test on such data? It's been a while, but last time I looked I didn't find any Pac Bio mock data, or data from samples sequenced on both Illumina (as a sort of reference) and Pac Bio.

One consideration would whether the alignment parameters need to be adjusted for the much longer sequences and error-modes of PacBio? 

The larger concern relates the fundamental reliance of DADA2 ASV inference on the presence of fully error-free reads. Would such reads to be rare (or even absent) in Pac Bio long-reads? If so, the DADA2 approach won't work. If there are a reasonably number of error-free reads, it should work, and it would just be a matter of potentially tweaking parameters appropriately.

**Comment by joey711** [comment] 2017-11-29 16:52
Even for CCR reads, the error rates per position is still pretty high and the length comparatively long, so the probability of a CCR being prefect is low. Too low for dada2 afaict. 

We have some paired 16S illumina and PacBio data, and are in the process of rounding out this comparison, but the differences in per position and per read error rates are pretty clear.

I'll see if I can get my colleague who has worked a lot on the pac bio side to comment...

**Comment by JacobRPrice** [comment] 2017-11-30 14:53
Thank you for your responses. It sounds like this is still an open question, or at least maybe possible in the future with improvements to the SMRT cell technology. 

@benjjneb 's response hints at another potential challenge in analyzing PacBio data. The number of total reads obtained from the run is physically limited by the number of ZMW on each cell. If the samples have very high diversity, even with good per position read quality, there may be very few error-free reads available for dada2 to build the error model and carry out ASV identification. 

I've been considering that one solution could be to trim the full length 16s reads from the PacBio such that only the variable regions sequenced on MiSeq are present (V3-4 in our case). This would significantly reduce the length of the reads that need to be error-free and "increase" the number of error-free reads that are present in the data set. I'm using quotation marks because it doesn't actually improve the reads, just removes opportunities (positions) where errors may have occurred. Obviously this is a suboptimal solution because we want to use full length 16s!

@joey711 If your collaborator is willing to chime in, I'd be all ears!

Thanks again.

**Comment by joey711** [comment] 2017-12-05 01:53
Okay, so the colleague to whom I was referring is [Fanny Perraudeau](https://github.com/fperraudeau) @fperraudeau , and her bioarxiv paper was just posted tonight:

https://www.biorxiv.org/content/early/2017/12/04/228619

I know she's interested in feedback.

**Comment by benjjneb** [comment] 2018-02-16 21:05
We are looking for PacBio CCS amplicon data, preferably of the 16S gene, that we could use for testing and development of a "long-read" version of DADA2.

If anyone has something appropriate available, we'd love to chat! The newer the PacBio instrument/chemistry the better, as my understanding is that their accuracy has improved a fair amount over the past few years.

**Comment by JacobRPrice** [comment] 2018-02-16 21:54
Hi @benjjneb,
We ( @cmsales ) have 32 samples that were sequenced (full length 16S) on PacBio last year. I'm not sure what chemistry version was used, but I could get the particulars. If you're interested could you let us know what files and information you would need from us (either on this thread or via email jrp355@drexel.edu)?

**Comment by benjjneb** [comment] 2018-02-16 22:13
For our dev purposes, we will be interested in the details of the PacBio machine/chemistry, the amplicon protocol, and gross sample metadata (e.g. what is the "type" of the samples, like mock or control or soil or etc.). We don't need more detailed sample metadata.

We also would want to work with the raw Pac Bio data format, so that we can modify the extraction of CCS reads (for example by requiring more/less consensus passes).

**Comment by JacobRPrice** [comment] 2018-02-16 23:09
I'll reach out to the sequencing group first thing on Monday and touch base with you when I hear back.

**Comment by JacobRPrice** [comment] 2018-02-22 22:28
Hi @benjjneb I have the data all together. How do you want me to send them to you (they're pretty big)? Would me uploading them to a github repo be sufficient?

**Comment by benjjneb** [comment] 2018-02-24 17:36
I suspect they will be too big for a github repo.

Would it be possible on your end to copy them from your server to ours using `scp`?

**Comment by JacobRPrice** [comment] 2018-02-25 13:04
Sure thing. Can you email me what server/directory you'd like me to copy them to?

**Comment by benjjneb** [comment] 2018-02-26 13:55
I think I might need to get you a guest account on the server.
I'll follow-up on email once I get that sorted out.

**Comment by chassenr** [comment] 2018-05-26 10:37
Hi,
have there been any updates regarding using dada2 for full length 16S PacBio data? I am also working with such a data set and would love to try analyzing it with dada2. However, dada2 1.8 does not seem to support long sequences which aren't Illumina encoded yet.

Thank you very much!

Cheers,
Christiane

**Comment by benjjneb** [comment] 2018-05-28 22:36
@chassenr It's something we are looking at, but don't have a usable update yet. Although, in what way did dada2 1.8 not work with long sequences? Did it fail to import them or somewhere else?

**Comment by chassenr** [comment] 2018-05-29 05:57
@benjjneb Importing and trimming the sequences worked as expected. The FilterAndTrim command also recognized the quality encoding (sanger) correctly. However, learnErrors() produced the following error message:
```
Error in dada_uniques(names(derep[[i]]$uniques), unname(derep[[i]]$uniques),:
Input sequences exceed the maximum allowed string length.
In addition: Warning message:
In dada(drps, err = NULL, errorEstimationFunction = errorEstimationFunction,:
derep$quals matrix has Phred Quality Scores >45. For Illumina 1.8 or earlier, this is unexpected.
```

**Comment by benjjneb** [comment] 2018-05-29 13:14
@chassenr Yes, we bumped the max sequence length up to 1600 in the 1.8 release but we need to do a little refactoring to go even longer.

The issue is purely technical: In the C code I set all the buffer sizes to the maximum sequence length, and I need to ensure that raising the buffer size doesn't run into limits with the stack size, and/or move the larger buffers to dynamically allocated memory.

**Comment by chassenr** [comment] 2018-05-29 16:17
@benjjneb Since >98% of my sequences are shorter than 1600bp, I will remove the few long reads (which may also represent sequencing errors) for now and try again. Thanks!

**Comment by FFoQS90** [comment] 2018-08-02 08:53
Hi @benjjneb,
I am also working on a dataset with the 16S of the same samples sequenced with Illumina MiSeq V3-V4 and with Pacbio SMRT Sequel (full-length) on the newest chemistry. Dada2 would be great to analyze and compare them. Did you make any progress on the Pacbio side of things? 
My group would also like to contribute by sharing our data with you if that would help.
Let me know if you are still interested in that!

**Comment by benjjneb** [comment] 2018-08-15 16:34
> Is using dada2 on PacBio SMRT Cell data feasible?

Short answer. Yes.

Long answer. Our preprint describing this is out today: https://www.biorxiv.org/content/early/2018/08/15/392332

Caveats. You should get version 1.9.1, and it probably won't work well (or at all) for early PacBio data, i.e. data on pre-P6C4 chemistries, and that was processed with old software versions (when it was named SMRT Portal rather than SMRT Link).

**Closed** 2018-08-20 20:52 UTC
