### ISSUE TITLE
Errors with learnErrors -related to new R version?

### ISSUE THREAD

**Issue by cchen1** [benjjneb/dada2#1850] opened 2023-11-10 20:02 UTC
I tried to follow the DADA2 Pipeline Tutorial but got segfault error messages when I reached the learnError step:

R version 4.3.2 (2023-10-31) -- "Eye Holes"
Copyright (C) 2023 The R Foundation for Statistical Computing
Platform: x86_64-apple-darwin20 (64-bit)

[R.app GUI 1.80 (8281) x86_64-apple-darwin20]

[Workspace restored from /Users/soil/.RData]
[History restored from /Users/soil/.Rapp.history]

> library(dada2); packageVersion("dada2")
Loading required package: Rcpp
[1] ‘1.29.0’
> 
> path <- "/Users/soil/Downloads/MiSeq_SOP" # CHANGE ME to the directory containing the fastq files after unzipping
> 
> list.files(path)
 [1] "F3D0_S188_L001_R1_001.fastq"   "F3D0_S188_L001_R2_001.fastq"   "F3D1_S189_L001_R1_001.fastq"   "F3D1_S189_L001_R2_001.fastq"   "F3D141_S207_L001_R1_001.fastq" "F3D141_S207_L001_R2_001.fastq"
 [7] "F3D142_S208_L001_R1_001.fastq" "F3D142_S208_L001_R2_001.fastq" "F3D143_S209_L001_R1_001.fastq" "F3D143_S209_L001_R2_001.fastq" "F3D144_S210_L001_R1_001.fastq" "F3D144_S210_L001_R2_001.fastq"
[13] "F3D145_S211_L001_R1_001.fastq" "F3D145_S211_L001_R2_001.fastq" "F3D146_S212_L001_R1_001.fastq" "F3D146_S212_L001_R2_001.fastq" "F3D147_S213_L001_R1_001.fastq" "F3D147_S213_L001_R2_001.fastq"
[19] "F3D148_S214_L001_R1_001.fastq" "F3D148_S214_L001_R2_001.fastq" "F3D149_S215_L001_R1_001.fastq" "F3D149_S215_L001_R2_001.fastq" "F3D150_S216_L001_R1_001.fastq" "F3D150_S216_L001_R2_001.fastq"
[25] "F3D2_S190_L001_R1_001.fastq"   "F3D2_S190_L001_R2_001.fastq"   "F3D3_S191_L001_R1_001.fastq"   "F3D3_S191_L001_R2_001.fastq"   "F3D5_S193_L001_R1_001.fastq"   "F3D5_S193_L001_R2_001.fastq"  
[31] "F3D6_S194_L001_R1_001.fastq"   "F3D6_S194_L001_R2_001.fastq"   "F3D7_S195_L001_R1_001.fastq"   "F3D7_S195_L001_R2_001.fastq"   "F3D8_S196_L001_R1_001.fastq"   "F3D8_S196_L001_R2_001.fastq"  
[37] "F3D9_S197_L001_R1_001.fastq"   "F3D9_S197_L001_R2_001.fastq"   "filtered"                      "HMP_MOCK.v35.fasta"            "Mock_S280_L001_R1_001.fastq"   "Mock_S280_L001_R2_001.fastq"  
[43] "mouse.dpw.metadata"            "mouse.time.design"             "stability.batch"               "stability.files"              
> 
> 
> # Place filtered files in filtered/ subdirectory
> filtFs <- file.path(path, "filtered", paste0(sample.names, "_F_filt.fastq.gz"))
> filtRs <- file.path(path, "filtered", paste0(sample.names, "_R_filt.fastq.gz"))
> names(filtFs) <- sample.names
> names(filtRs) <- sample.names
> 
> out <- filterAndTrim(fnFs, filtFs, fnRs, filtRs, truncLen=c(240,160),
+               maxN=0, maxEE=c(2,2), truncQ=2, rm.phix=TRUE,
+               compress=TRUE, multithread=TRUE) # On Windows set multithread=FALSE
> head(out)
                              reads.in reads.out
F3D0_S188_L001_R1_001.fastq       7793      7113
F3D1_S189_L001_R1_001.fastq       5869      5299
F3D141_S207_L001_R1_001.fastq     5958      5463
F3D142_S208_L001_R1_001.fastq     3183      2914
F3D143_S209_L001_R1_001.fastq     3178      2941
F3D144_S210_L001_R1_001.fastq     4827      4312
> 
> errF <- learnErrors(filtFs, multithread=TRUE)
33514080 total bases in 139642 reads from 20 samples will be used for learning the error rates.

 *** caught segfault ***
address 0x9ffffffe7, cause 'memory not mapped'

Traceback:
 1: dada_uniques(names(drpi$uniques), unname(drpi$uniques), names(drpi$uniques) %in%     c(priors, pseudo_priors), erri, unname(t(drpi$quals)), opts[["MATCH"]],     opts[["MISMATCH"]], opts[["GAP_PENALTY"]], opts[["USE_KMERS"]],     opts[["KDIST_CUTOFF"]], opts[["BAND_SIZE"]], opts[["OMEGA_A"]],     opts[["OMEGA_P"]], opts[["OMEGA_C"]], opts[["DETECT_SINGLETONS"]],     if (initializeErr) {        1    } else {        opts[["MAX_CLUST"]]    }, opts[["MIN_FOLD"]], opts[["MIN_HAMMING"]], opts[["MIN_ABUNDANCE"]],     TRUE, FALSE, opts[["VECTORIZED_ALIGNMENT"]], opts[["HOMOPOLYMER_GAP_PENALTY"]],     multithread, (verbose >= 2), opts[["SSE"]], opts[["GAPLESS"]],     opts[["GREEDY"]])
 2: dada(drps, err = NULL, errorEstimationFunction = errorEstimationFunction,     selfConsist = TRUE, multithread = multithread, verbose = verbose,     MAX_CONSIST = MAX_CONSIST, OMEGA_C = OMEGA_C, ...)
 3: learnErrors(filtFs, multithread = TRUE)

Possible actions:
1: abort (with core dump, if enabled)
2: normal R exit
3: exit R without saving workspace
4: exit R saving workspace
Selection: 
Selection:

**Comment by benjjneb** [comment] 2023-11-11 21:56
This looks like a duplicate of https://github.com/benjjneb/dada2/issues/1645#issuecomment-1802562663

Currently unresolved. See that thread for more info.

**Closed** 2024-05-27 20:28 UTC
