### ISSUE TITLE
wide distribution of sequence lengths after merging

### ISSUE THREAD

**Issue by reidgrahamgriggs** [benjjneb/dada2#73] opened 2016-05-18 19:43 UTC
Hi @benjjneb ,

I'm repeatedly seeing a wide distribution of sequence lengths after merging when running dada2 on my data. I thought this could be due to the variance of sequnce quality by sample, so I tested this by running a single high quality sample. Unfortunately I've come to the same result which leads me to believe that this is either non-specific priming, another data issue, or a problem with my implementation of your code. Could you help me troubleshoot this?  I've attached a link to the higher quality files.

https://www.dropbox.com/sh/hwrtv1zg1v4dm3m/AAAHnrzfZAoHy6IZarFI0h6ca?dl=0

my filtering parameters:
fastqPairedFilter(c(fnF, fnR), c(filtF, filtR),
                  trimLeft=c(10, 10),matchIDs=TRUE, truncLen=c(240,225),
                  maxEE=2, maxN=0, rm.phix=TRUE,minQ = 10,
                  verbose=TRUE)
output ex:
large set of samples
table(nchar(colnames(seqtabIPAC)))
230  231  232  233  234  235  236  237  238  239  240  241  244  254  255  256  271  273  275 2076   
 4    4    8   20    2   11    2    8    3    7   27    6    1    4   13    1    1    1 
277  279  280  287  289  290  291  294  296  297  303  304  305  307  308  309  310  313  315 
1    7    1    1    1    1    1    1    2    1    1    3    3    2    2    1    2    1    4 
 317  319  321  327  332  335  337  338  342  345  347  350  353  354  355  356  357  358  359 
 1    1    2    1    1    1    1    1    2    1    2    1    1    1    2    1    2    3    1 

single, high qual sample
table(nchar(colnames(seq_single)))
230 231 232 234 237 242 244 249 250 254 255 260 261 265 271 277 278 420 422 424 
  8   2   1   1   1   1   1   1   1   1   2   1   1   3   1   1   1   1   4   2 

If you see no issues w the code or data, do you recommend proceeding by removing sequences w length outside a certain range?

Thank you very much!

**Comment by benjjneb** [comment] 2016-05-18 19:52
Hi Reid,
Two things would be helpful:

Could you share a .rds file of your sequence table in the dropbox rather than the raw data? (`saveRDS`)

Could you see how many unique sequences there are if you restrict to just the first 230 nts? (`length(unique(substr(getSequences(seqtabIPAC),1,230)))` vs. `length(getSequences(seqtabIPAC))`)

This sort of thing can be caused by non-specific priming, which would be my first guess as these are pairs of reads that are being successfully merged. In my previous experience with this, it has been the reverse primer that is the issue, but that can be checked from the sequence table.

**Comment by reidgrahamgriggs** [comment] 2016-05-18 20:51
Hi Ben,

Thanks for the prompt reply.  I've added the .rds files to the dropbox
folder.  Heres the requested info:

Large sample set(seqtabIPAC)
2257, 2261
Single sample(seq_single)
32, 35

I appreciate you looking into this.  My wondering if this could be stemming
from something other than non-specific priming comes from the drastic
reduction of sequences/reads in the output.  I know that even in the
tutorials dada filters sequences/reads by an order of magnitude, but this
is an example of some of the best quality data as identified by the
graphing feature.  Some samples begin with >10,000 reads and are reduced to
<10 after merging in the larger data set.
Derep-
Dereplicating sequence entries in Fastq file: 15JLSP057_R1.fq.gz
Encountered 5778 unique sequences from 9569 total sequences read.
Merge-
415 paired-reads (in 41 unique pairings) successfully merged out of 9569
(in 1105 pairings) input.


Thanks,
Reid

**Comment by benjjneb** [comment] 2016-05-18 21:20
One more question: What primers are you using (eg. 515F/806R)? In particular, how far apart are they?

**Comment by reidgrahamgriggs** [comment] 2016-05-18 21:48
Heres what I'm gathering from the mapping file that was shared w me.  The
forward primer used was: CCTACGGGNGGCWGCAG, and the reverse was:
GACTACHVGGGTATCTAATCC.

I'm unsure of how far apart they were, but I believe is V3/V4.  Sorry I
dont have more info, I joined this project in the middle.  I can ask about
more specifics if its helpful and this doesn't answer your question.

Thanks,
Reid

**Comment by benjjneb** [comment] 2016-05-19 04:38
To be honest this data looks basically unusable to me. One thing to be aware of is that since you are using what looks like the 341F/805R primer set, which means the reads start ~465 nts apart from each other, therefor you can't trim the ends hardly at all if you want to keep an overlap between the reads. So I ran the following revised processing on the single samples you provided:

```
fastqPairedFilter(c(fnF, fnR), c(filtF2, filtR2),
                  trimLeft=c(10, 10),matchIDs=TRUE, truncLen=c(250,240),
                  maxEE=c(2,4), maxN=0, rm.phix=TRUE,minQ = 10,
                  verbose=TRUE)

drpF2 <- derepFastq(filtF2, verbose=TRUE)
drpR2 <- derepFastq(filtR2, verbose=TRUE)

ddF2 <- dada(drpF2, err=NULL, selfConsist=TRUE)
ddR2 <- dada(drpR2, err=NULL, selfConsist=TRUE)

mm2 <- mergePairs(ddF2, drpF2, ddR2, drpR2, verbose=TRUE)
```

Only 480 reads out of 11067 made it through merging. So I BLASTed the top 20 sequences from ddF2 (`dada2:::pfasta(ddF2$sequence[1:20]` then BLAST against nt at NCBI). 19/20 hit **nothing** and 1/20 hits a mitochondrion. Same story for the reverse reads.

When I BLAST the merged reads, things are very slightly better: There were 5 hits to bacterial 16S corresponding to the 5 merged sequences of 445-447 nucleotides in length (the expected length for these primers after trimming the first 10 nts of F/R).

So, to get the 16S signal out of this data, one can subset the merged data.frame on this length window:

```
mm <- mm2[nchar(mm2$sequence) %in% seq(440,450),]
```

At which point there are 151 reads in 5 sequences left, which is why this data looks unusable to me.

**Comment by reidgrahamgriggs** [comment] 2016-05-19 18:35
Do you recommend attemping with the joined reads from the sequencer or does that undermine the whole goal of the pipeline?

We are trying to look at sub-genus level variation, a problem for which I think dada2 is ideally suited.  Its certainly frustrating that QIIME is calling lots of variation here, while the data doesn't stand up to the stringency of dada2.  It seems to me that assigning taxa at a deeper taxonomic rank with any certainty (whether that means calling them species or real 16s variants) requires the type of reoslution/ statistical reasoning provided by dada2.  

I'm wondering how to proceed. It seems that I could use QIIME with BLAST for added specificity and then import the .biom files into R for further analysis using the pipeline described here (http://psb.stanford.edu/psb-online/proceedings/psb16/callahan.pdf).  My second idea would be to use the joined reads which still retain quality information in dada2 and attmept to filter them with dada() and removebimerasdenovo().

Thanks again for the added considerations noted in this thread, and the troubleshooting.

**Comment by benjjneb** [comment] 2016-05-19 19:29
Hi Reid,
I'm not sure what your study is, and I've only looked at the one sample you shared, but as far as I can tell that sample is not 16S data. It mostly doesn't BLAST against anything in nt. That is a bad sign.

The QIIME workflow may very well produce an output, but that doesn't guarantee it is meaningful. You can get an output from the dada2 pipeline by just using the forward reads, but again -- given what I've seen I don't think it's meaningful.

Maybe the other samples aren't like this one?

**Comment by reidgrahamgriggs** [comment] 2016-05-19 21:00
Hi Ben,

I agree, that is a bad sign.  I think I'll proceed by using BLAST on forward reads as a fact check. Theres ~100 samples in this set so I'm hoping that there some meaningfull data there.  

Is there a good rule of thumb for determining if the dada pipeline output reflects real 16S signal? Should all sequnces be identifiable by BLAST, or at least be a '1 off'?

**Comment by benjjneb** [comment] 2016-05-19 22:28
Hi Reid,

To clarify, when I am BLASTing these sequences (megablast, default E=10) they are hitting **nothing**. I don't mean that Blast isn't finding any exact matches, I mean BLAST returns no hits period, at any level of identity.

That doesn't happen for 16S sequences.

**Comment by reidgrahamgriggs** [comment] 2016-05-20 01:08
Right, thanks for the clarification.  I was meaning that if I encounter a similiar situation in future samples (eg 0 BLAST hits), theres a serious issue and the whole sample should be regarded as useless/not 16S sequences.

**Closed** 2016-06-03 18:15 UTC
