### ISSUE TITLE
Error in simpleLoess(y, x, w, span, degree = degree, parametric = parametric, : span is too small

### ISSUE THREAD

**Issue by shrukane** [benjjneb/dada2#171] opened 2016-12-22 06:54 UTC
Hi, 
Thanks for writing this package. I am getting the following error after dereplication
**Command -**
dadaFs.lrn <- dada(derepFs, err=NULL, selfConsist = TRUE, multithread=TRUE)
**Error -**
Initial error matrix unspecified. Error rates will be initialized to the maximum possible estimate from this data.
Initializing error rates to maximum possible estimate.
Error in simpleLoess(y, x, w, span, degree = degree, parametric = parametric,  : 
  span is too small
In addition: Warning message:
In dada(derepFs, err = NULL, selfConsist = TRUE, multithread = TRUE) :
  multithread is not a valid DADA option.

The dataset I am using is simulated manually from varying the proportion of 5 distinctly related bacterial genera's. 
Is the error model not suited for sparsely related species ? Is there any other error model that I must use instead ? 

Thanks for looking into this.

Shruti

**Comment by benjjneb** [comment] 2016-12-22 18:15
How are errors being added to reads in your simulated dataset?

**Comment by benjjneb** [comment] 2017-01-10 17:58
Closing, but feel free to reopen if still a problem.

The issue is that the simulated errors you have added to your reads are not well distributed amongst the quality scores, so the loess fit over quality scores is failing. This can be fixed, but we need more information on the form of the errors you are adding to your simulated data.

**Closed by benjjneb** 2017-01-10 17:58 UTC

**Comment by shrukane** [comment] 2017-01-13 05:48
Hi @benjjneb, sorry for the late reply. Was trying to figure out at my end. So in my experiment, I have taken only 5 bacteria's (distinctly related) and varied their proportion. I have not simulated any error's. Although after your suggestion I manually introduced some noise after which the above error was resolved. But I am still not able to detect the bacteria which I had introduced in smaller proportions. Is 5 too less a number to introduce to the tool? Is there a relation between sensitivity and diversity? Like if I introduce more diversity will the sensitivity towards bacteria's in lower proportion increase? Also, would you suggest adding errors using other software programs? I would be grateful for any suggestions from you.
Thanks 
Shruti

**Comment by shrukane** [comment] 2017-01-17 09:28
Thank you @benjjneb, art solved the error model problem. My simulation algorithm was the cause of my issues. 

Shruti

**Comment by emmina1998** [comment] 2022-03-03 14:05
Warning in simpleLoess(y, x, w, span, degree = degree, parametric = parametric,  :
  Chernobyl! trL>n 16
Warning in simpleLoess(y, x, w, span, degree = degree, parametric = parametric,  :
  Chernobyl! trL>n 16
Warning in sqrt(sum.squares/one.delta) : NaNs produced
Warning in simpleLoess(y, x, w, span, degree = degree, parametric = parametric,  :
  pseudoinverse used at 2845
Warning in simpleLoess(y, x, w, span, degree = degree, parametric = parametric,  :
  neighborhood radius 417
Warning in simpleLoess(y, x, w, span, degree = degree, parametric = parametric,  :
  reciprocal condition number  0

Hi, someone can help me? 
I don't understand where the problem is. 
Thank you

**Comment by benjjneb** [comment] 2022-03-10 03:35
@emmina1998 It looks like you are getting warnings from `learnErrors` that the loess fitting is struggling to match the data in some way. They are just warnings, so you can potentially ignore them, but it would be best to look at the error models to see if they make sense.

In the future,  you should provide more context when asking for assistance. For example, the exact commands you are executing, and some background on the data you are working with.

**Comment by ziahasanz** [comment] 2022-04-15 23:13
Hi, after giving the below command, I'm getting the warning.
> s1f <- NormalizeData(s1f, normalization.method = "LogNormalize", scale.factor = 1e4)
Performing log-normalization
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
> s1f <- FindVariableFeatures(s1f, selection.method = "vst", nfeatures = 2000)
Calculating gene variances
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Calculating feature variances of standardized and clipped values
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Warning messages:
1: In simpleLoess(y, x, w, span, degree = degree, parametric = parametric,  :
  at  -0.91461
2: In simpleLoess(y, x, w, span, degree = degree, parametric = parametric,  :
  radius  0.00013262
3: In simpleLoess(y, x, w, span, degree = degree, parametric = parametric,  :
  all data on boundary of neighborhood. make span bigger
4: In simpleLoess(y, x, w, span, degree = degree, parametric = parametric,  :
  pseudoinverse used at -0.91461
5: In simpleLoess(y, x, w, span, degree = degree, parametric = parametric,  :
  neighborhood radius 0.011516
6: In simpleLoess(y, x, w, span, degree = degree, parametric = parametric,  :
  reciprocal condition number  1
7: In simpleLoess(y, x, w, span, degree = degree, parametric = parametric,  :
  zero-width neighborhood. make span bigger
8: In simpleLoess(y, x, w, span, degree = degree, parametric = parametric,  :
  There are other near singularities as well. 0.031008

**Comment by benjjneb** [comment] 2022-04-18 13:26
@ziahasanz It doesn't seem that your code here is related to the dada2 R package, so this isn't the right venue to ask for help on these loess warnings. I'd try looking for the support information for the specific package you are using.
