### ISSUE TITLE
Error: logical subscript contains NAs in FilterAndTrim

### ISSUE THREAD

**Issue by Listen-Lii** [benjjneb/dada2#388] opened 2017-12-29 03:18 UTC
Hi~I am a novice to DADA2.
When run FilterAnd Trim, I got Error: logical subscript contains NAs in FilterAndTrim.
My Input fnFs and fnRs sequences were like this:
![1](https://user-images.githubusercontent.com/34201684/34428630-e1c14c1a-ec89-11e7-8bf4-032a4556c9e2.png)
Command:
out <- filterAndTrim(fnFs, filtFs, fnRs, filtRs, maxN=0, maxEE=c(2,2), truncQ=2, rm.phix=TRUE,minQ=20, compress=TRUE, multithread=FALSE,verbose=TRUE) 
How to deal with this?

**Comment by benjjneb** [comment] 2017-12-30 19:52
Not sure. Can you report the output of the following (after loading the dada2 package)?

```
packageVersion("dada2")
R.version
packageVersion("ShortRead")
```

**Comment by bowmanjeffs** [comment] 2018-01-10 15:49
I'm having the same issue.  It seems to be related (in my case) to the minQ parameter.  When minQ is set to default, the command completes without error.  When minQ = 30, the command also completes without error.  When minQ is set to any value between 0 and 30 (e.g. 25) the command fails with the specified error. 

```
> packageVersion("dada2")
[1] ‘1.6.0’
> R.version
               _
platform       x86_64-pc-linux-gnu
arch           x86_64
os             linux-gnu
system         x86_64, linux-gnu
status
major          3
minor          4.3
year           2017
month          11
day            30
svn rev        73796
language       R
version.string R version 3.4.3 (2017-11-30)
nickname       Kite-Eating Tree
> packageVersion("ShortRead")
[1] ‘1.36.0’
>
```

**Comment by benjjneb** [comment] 2018-01-10 22:04
Can you tell me a little bit about your data. Is it e.g. Illumina Miseq 2x250?

Your packages look up to date. Can you share an example file, preferably a single file, that causes this error?

**Comment by bowmanjeffs** [comment] 2018-01-10 23:09
Example of forward/reverse read pair that is failing.  This is Illumina MiSeq 151x151
[demultiplexed.zip](https://github.com/benjjneb/dada2/files/1620694/demultiplexed.zip)

**Comment by benjjneb** [comment] 2018-01-11 16:46
Found the bug, and it is fixed in the devel branch. You can install the fixed version from github with:

```
library(devtools)
install_github("benjjneb/dada2")
```

**Comment by benjjneb** [comment] 2018-10-22 12:55
Thanks for the report @colinaverill 

I have not seen this come up in the current versions of the package, so I am very interested.

Would you be willing to try to narrow this down to a single sample? I suspect there is just one or a few samples causing this. Could you try looping through the samples, one at a time, to find one throwing this error? At that point, it would be great if you could share that one sample, as I think I will need to dig into this one as I don't have any inspiration striking me.

**Comment by colinaverill** [comment] 2018-10-22 17:44
Thanks for the reply. I have confirmed that this particular sample with a single sequence throws this error. Its in `.fastq` format, but I have renamed the extension to `.txt` so it would upload directly here. I've also copied the file contents below since its a sample with just one sequence.

```
@BART_001-O-7-1-20140619-gen_47983 M02149:248:000000000-AHBR7:1:1101:14574:25558 1:N:0:0 orig_bc=TTGGGCGTGAAC new_bc=TTGGGCGTGAAC bc_diffs=0
AGGTAAAACCTCTTATGACGCTGACAACCGTCCTTTACTTGTCATGCGCTCTAATCTCTGGGCATCTGGCTATGATGTTGATGGAACTGACCAAACGTCGTTAGGCCAGTTTTCTGGTCGTGTTCAACAGACCTATAAACATTCTGTGCCGCGTTTCTTTGTTCCTGAGCATGGCACTATGTTTACTCTTGCGCTTGTTCGTTTTCCGCCTACTGCGACTAAAGAGATTCAGTACCTTAACGCTAAAGGTGCTTTGACTTATACCGATATTGCTGGCGACCCTGTTTTGTATGGCAACTTGCCGCCGCGTGAAATTTCTATGAAGGATGTTTTCCGTTCTGGTGATTCGTCTAAGAAGTTTAAGATTGCTGAGGGTCAGTG
+
CCCCBFFFFBBBBGGFFFGGGFGGHHHHGGGGGGHHHHHHHHHHHHHGGGGHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHGHHGGGHGHHHHHHHHHHHHHHHGGGHHHHHHHHHHHHHHHHHHHHHH&GHHHHGGGGGGHHHHHHHHHHHHGHHHHHHHHHHHHHHHGHHHHHGHGGGGGHHHGGHGGHHGGGGGGGGGGGHHHGHHHHGGHHHHHGFFFGGGGHHGHHGHHHGHGFHHHHHGFHDGGHG2HHHGGGGGGHHGHHHHHHHHHGHHHHHHHGGGGGGGGGHHHHGHHGHHHHHHHHHHHHHEHFGGGGGHHHHHHHHGHGGGHHGHHHHHHHHGGGGGGBFFGCACFFFFBBABB
```




[BART_001-O-7-1-20140619-gen.txt](https://github.com/benjjneb/dada2/files/2502465/BART_001-O-7-1-20140619-gen.txt)

**Comment by colinaverill** [comment] 2018-10-22 18:19
Okay, I have confirmed that this is driven by a handful of samples that contain only a single sequence (4 lines in a file). I wrote code to exclude these samples and the function now runs fine. Thanks for your help with this! I imagine this problem may trip up other users in the future.

**Comment by benjjneb** [comment] 2018-10-22 22:34
> Changing maxEE = c(2,2) to maxEE = 2 also solved this problem, and no longer required me to remove files with only one sequence.

Well that explains why I was failing to replicate this! Thanks for tracking it down so precisely. That looks like a bug, that should either be handled gracefully, or the function should stop and give useful feedback.

**Closed** 2019-03-20 15:11 UTC
Labels: bug
