### ISSUE TITLE
Different taxa assignment when using GTDB full or Genus level files

### ISSUE THREAD

**Issue by ramay** [benjjneb/dada2#1699] opened 2023-02-11 07:48 UTC
Hi, 
I am trying to assign taxonomy to my sequence table using assignTaxonomy function  but with either Genus level GTDB (GTDB_bac120_arc53_ssu_r207_Genus.fa.gz) or full taxonomy (GTDB_bac120_arc53_ssu_r207_fullTaxo.fa.gz). This difference is also seen at the species level assignment which I did with the species level file using the addSpecies function.

For some strange reason, I get different taxonomy for some ASVs. I am going to use two sequences here as an example. 

With Genus level file I get:
```
set.seed(100)
> taxa<-assignTaxonomy(seqs = seq[,c(58,60)],refFasta = "~/Downloads/dbs/GTDB_bac120_arc53_ssu_r207_Genus.fa.gz",
+                      outputBootstraps = T,multithread = T
+ )
> print(unname(taxa$tax))
     [,1]       [,2]             [,3]                  [,4]               [,5]                 [,6]         
[1,] "Bacteria" "Proteobacteria" "Gammaproteobacteria" "Enterobacterales" "Enterobacteriaceae" "Escherichia"
[2,] "Bacteria" "Firmicutes_A"   "Clostridia"          "Lachnospirales"   "Lachnospiraceae"    "FD2005"     
> print(unname(taxa$boot))
     [,1] [,2] [,3] [,4] [,5] [,6]
[1,]  100  100  100  100  100   92
[2,]  100   99   99   99   99   68

> taxa_species<-addSpecies(taxa$tax,refFasta = "~/Downloads/dbs/GTDB_bac120_arc53_ssu_r207_Species.fa.gz",allowMultiple = T)
> taxa_species[,7]
TGGGGAATATTGCACAATGGGCGCAAGCCTGATGCAGCCATGCCGCGTGTATGAAGAAGGCCTTCGGGTTGTAAAGTACTTTCAGCGGGG
AGGAAGGGAGTAAAGTTAATACCTTTGCTCATTGACGTTACCCGCAGAAGAAGCACCGGCTAACTCCGTGCCAGCAGCCGCGGTAATACG
GAGGGTGCAAGCGTTAATCGGAATTACTGGGCGTAAAGCGCACGCAGGCGGTTTGTTAAGTCAGATGTGAAATCCCCGGGCTCAACCTG
GGAACTGCATCTGATACTGGCAAGCTTGAGTCTCGTAGAGGGGGGTAGAATTCCAGGTGTAGCGGTGAAATGCGTAGAGATCTGGAGGAA
TACCGGTGGCGAAGGCGGCCCCCTGGACGAAGACTGACGCTCAGGTGCGAAAGCGTGGGGAGCAAACAGG 
 NA

TGGGGAATATTGCACAATGGGCGAAAGCCTGATGCAGCGACGCCGCGTGAGCGAAGAAGTATTTCGGTATGTAAAGCTCTATCAGAAGGG
AAGAAAATGACGGTACCTTACTAAGAAGCTCCGGCTAAATACGTGCCAGCAGCCGCGGTAATACGTATGGAGCAAGCGTTATCCGGATTTA
CTGGGTGTAAAGGGAGTGTAGGCGGCACTATAAGTCTGATGTGAAAACCTAAGGCTTAACCATAGGATTGCATTGGAAACTGTAGAGCTGG
AGTATCGGAGAGGCAAGCGGAATTCCTGGTGTAGTGGTGAAATACGTAGATATCAGGAAGAACATCGGTGGCGAAGGCGGCTTGCTGGAC
GATAACTGACGCTAAGGCTCGAAAGCGTGGGAAGCGAACAGG 
NA 
> 

```
With full taxa file I get:
```
> set.seed(100)
> taxa<-assignTaxonomy(seqs = seq[,c(58,60)],refFasta = "~/Downloads/dbs/GTDB_bac120_arc53_ssu_r207_fullTaxo.fa.gz",
+                      outputBootstraps = T,multithread = T
+ )
> print(unname(taxa$tax))
     [,1]       [,2]             [,3]                  [,4]             [,5]              [,6]   [,7]                                  
[1,] "Bacteria" "Proteobacteria" "Gammaproteobacteria" NA               NA                NA     NA                                    
[2,] "Bacteria" "Firmicutes_A"   "Clostridia"          "Lachnospirales" "Lachnospiraceae" "14-2" "14-2_sp001940225(RS_GCF_001940225_1)"
> print(unname(taxa$boot))
     [,1] [,2] [,3] [,4] [,5] [,6] [,7]
[1,]  100   65   65   43   43   43   14
[2,]  100  100  100  100  100   93   86
taxa_species<-addSpecies(taxa$tax,refFasta = "~/Downloads/dbs/GTDB_bac120_arc53_ssu_r207_Species.fa.gz",allowMultiple = T)
> taxa_species[,8]
TGGGGAATATTGCACAATGGGCGCAAGCCTGATGCAGCCATGCCGCGTGTATGAAGAAGGCCTTCGGGTTGTAAAGTACTTTCAGCGGGG
AGGAAGGGAGTAAAGTTAATACCTTTGCTCATTGACGTTACCCGCAGAAGAAGCACCGGCTAACTCCGTGCCAGCAGCCGCGGTAATACG
GAGGGTGCAAGCGTTAATCGGAATTACTGGGCGTAAAGCGCACGCAGGCGGTTTGTTAAGTCAGATGTGAAATCCCCGGGCTCAACCTG
GGAACTGCATCTGATACTGGCAAGCTTGAGTCTCGTAGAGGGGGGTAGAATTCCAGGTGTAGCGGTGAAATGCGTAGAGATCTGGAGGAA
TACCGGTGGCGAAGGCGGCCCCCTGGACGAAGACTGACGCTCAGGTGCGAAAGCGTGGGGAGCAAACAGG 
"coli/fergusonii/flagellatus/sp005843885/sp014237865/sp900764415/sp905197905"

TGGGGAATATTGCACAATGGGCGAAAGCCTGATGCAGCGACGCCGCGTGAGCGAAGAAGTATTTCGGTATGTAAAGCTCTATCAGAAGGG
AAGAAAATGACGGTACCTTACTAAGAAGCTCCGGCTAAATACGTGCCAGCAGCCGCGGTAATACGTATGGAGCAAGCGTTATCCGGATTTA
CTGGGTGTAAAGGGAGTGTAGGCGGCACTATAAGTCTGATGTGAAAACCTAAGGCTTAACCATAGGATTGCATTGGAAACTGTAGAGCTGG
AGTATCGGAGAGGCAAGCGGAATTCCTGGTGTAGTGGTGAAATACGTAGATATCAGGAAGAACATCGGTGGCGAAGGCGGCTTGCTGGAC
GATAACTGACGCTAAGGCTCGAAAGCGTGGGAAGCGAACAGG                                                                                                                  
NA
 
```

So the two problems are:

1. for the first sequence, the two files get taxonomy assigned to different levels. I have tried different seeds and with full taxo it never gets to beyond Class assignment. 
2. For the second sequence, both of them assign a different Genus but each file always assigns the same genus not matter how many times I run it or change the seed. 

3. When I take the assigned taxa based on the two reference files and use it with addSpecies function with the exact same Species level reference file I get different results. In one case I get NA for both ASVs and in the other case I get multiple assignments for one ASV

Can you please explain to me why the same GTDB database with exactly the same sequences would result in such differences. Also why is the same species taxanomy file and the function giving different results depending on what I taxa file I use in assignTaxonomy file. As far as I understood addSpecies uses the assignSpecies function which should just do an exact match. 

I have placed the gtdb files along with and seqtable rds object with these two sequences  here https://www.dropbox.com/sh/8466h249g04jqyj/AAAAgnYO9ElX8R8qk81vN6tYa?dl=0

Any help is much appreciated!!

Hena

**Comment by ramay** [comment] 2023-02-13 20:13
I found one mistake in my code where when passing the taxa$tax to addSpecies for fulltaxa file, I should have taken out column 7. When I leave it in the following code in addSpecies function  doesn't work and in column 8 which becomes Species.1 (becuase Species already exists) and then the next line of code fails
```
# If species column already exists then Species becomes Species.1
colnames(taxtab)[ncol(taxtab)] <- "Species"

# This statement fails
  taxtab[!gen.match, "Species"] <- NA_character_
```
However, even if RDP classifier assigns a different genus why should we not include the exact matched species to the taxonomy? I understand that we would not have all the taxa level but shouldn't there be a way to add these?

I still have not been able to figure out why I see differences  between Genus and full taxa GTDB file when using the RDP classifier. Any help on that will be much appreciated!

Hena

**Comment by ramay** [comment] 2023-02-14 00:31
I have figured out why the difference in  annotation at Genus level is happening with thes two files GTDB_bac120_arc53_ssu_r207_Genus.fa.gz or GTDB_bac120_arc53_ssu_r207_fullTaxo.fa.gz.

This is happening because in the Genus file there are non unquie sequence headers and the assignTaxonomy function uses unique() function on these headers and ends up with only one representative sequence for 14-2 Genus. Hence using the genus file RDP assigned FD2500 instead of 14-2.

I think it would be helpful (if not already done) to add this in dada2 taxonomy page that the assignTaxonomy function does select only one unique section or mention to check that fastq headers are unique. When we downloaded the GTDB file it just made sense to use the Genus level file with assignTaxonomy and Species level with addSpecies. 

Also would be useful for users to know that assignSpecies and addSpecies behave slightly differently. addSpecies does not add species that do not belong to the same genus as the RDP assigned genus while assignSpecies does not check for this and assigns species irrespective of the genus.

Hena

**Comment by benjjneb** [comment] 2023-02-14 19:55
Thanks for following up on this and updating us all with what you found!

Can you clarify what you mean by this?

> This is happening because in the Genus file there are non unquie sequence headers and the assignTaxonomy function uses unique() function on these headers and ends up with only one representative sequence for 14-2 Genus. Hence using the genus file RDP assigned FD2500 instead of 14-2.

What does a "non-unique sequence header" look like, format-wise? And does the description of how the dada2-formatted GTDB training fastas were generated (https://zenodo.org/record/6655692#.Y-vnB-zMJqs) fail to explain what is going on?

**Comment by ramay** [comment] 2023-02-15 17:29
Sorry for the confusion! I misunderstood some of the assignTaxonomy code and thought you were only taking unique headers by doing `  genus.unq <- unique(tax)`. I see that there is a table that has indices of all the sequences in ref.to.genus that will match the headers. So while my understanding is wrong the problem is still there.

I downloaded the genus level GTDB file from https://zenodo.org/record/6655692#.Y-vnB-zMJqs . If I use this file which as same header for multiple sequences, it fails to identify my input ASV as 14-2 at Genus level but assigns FD2005
Just to show you there are multiple  sequences in this file with the same header. This should not be a problem as you are using the ref.to.genus vector but for some reason it is.

```
gunzip -c  GTDB_bac120_arc53_ssu_r207_Genus.fa.gz | grep "Bacteria;Firmicutes_A;Clostridia;Lachnospirales;Lachnospiraceae;14-2;"
>Bacteria;Firmicutes_A;Clostridia;Lachnospirales;Lachnospiraceae;14-2;
>Bacteria;Firmicutes_A;Clostridia;Lachnospirales;Lachnospiraceae;14-2;
>Bacteria;Firmicutes_A;Clostridia;Lachnospirales;Lachnospiraceae;14-2;
>Bacteria;Firmicutes_A;Clostridia;Lachnospirales;Lachnospiraceae;14-2;
>Bacteria;Firmicutes_A;Clostridia;Lachnospirales;Lachnospiraceae;14-2;
>Bacteria;Firmicutes_A;Clostridia;Lachnospirales;Lachnospiraceae;14-2;
>Bacteria;Firmicutes_A;Clostridia;Lachnospirales;Lachnospiraceae;14-2;
>Bacteria;Firmicutes_A;Clostridia;Lachnospirales;Lachnospiraceae;14-2;
>Bacteria;Firmicutes_A;Clostridia;Lachnospirales;Lachnospiraceae;14-2;
>Bacteria;Firmicutes_A;Clostridia;Lachnospirales;Lachnospiraceae;14-2;
>Bacteria;Firmicutes_A;Clostridia;Lachnospirales;Lachnospiraceae;14-2;
>Bacteria;Firmicutes_A;Clostridia;Lachnospirales;Lachnospiraceae;14-2;
>Bacteria;Firmicutes_A;Clostridia;Lachnospirales;Lachnospiraceae;14-2;
>Bacteria;Firmicutes_A;Clostridia;Lachnospirales;Lachnospiraceae;14-2;
>Bacteria;Firmicutes_A;Clostridia;Lachnospirales;Lachnospiraceae;14-2;
>Bacteria;Firmicutes_A;Clostridia;Lachnospirales;Lachnospiraceae;14-2;
```
```
> assignTaxonomy(seqs = seq[,c(58,60)],refFasta = "~/Downloads/dbs/GTDB_bac120_arc53_ssu_r207_Genus.fa.gz",outputBootstraps = T,multithread = T)->tg
> unname(tg$tax)
     [,1]       [,2]             [,3]                  [,4]               [,5]                 [,6]         
[1,] "Bacteria" "Proteobacteria" "Gammaproteobacteria" "Enterobacterales" "Enterobacteriaceae" "Escherichia"
[2,] "Bacteria" "Firmicutes_A"   "Clostridia"          "Lachnospirales"   "Lachnospiraceae"    "FD2005"
```

Now as a sanity check I renamed these sequences by seqkit rename function so in my new fasta file they look like this:

```
cat GTDB_bac120_arc53_ssu_r207_Genus_renamed.fa | grep "Bacteria;Firmicutes_A;Clostridia;Lachnospirales;Lachnospiraceae;14-2"
>Bacteria;Firmicutes_A;Clostridia;Lachnospirales;Lachnospiraceae;14-2
>Bacteria;Firmicutes_A;Clostridia;Lachnospirales;Lachnospiraceae;14-2_2
>Bacteria;Firmicutes_A;Clostridia;Lachnospirales;Lachnospiraceae;14-2_3
>Bacteria;Firmicutes_A;Clostridia;Lachnospirales;Lachnospiraceae;14-2_4
>Bacteria;Firmicutes_A;Clostridia;Lachnospirales;Lachnospiraceae;14-2_5
>Bacteria;Firmicutes_A;Clostridia;Lachnospirales;Lachnospiraceae;14-2_6
>Bacteria;Firmicutes_A;Clostridia;Lachnospirales;Lachnospiraceae;14-2_7
>Bacteria;Firmicutes_A;Clostridia;Lachnospirales;Lachnospiraceae;14-2_8
>Bacteria;Firmicutes_A;Clostridia;Lachnospirales;Lachnospiraceae;14-2_9
>Bacteria;Firmicutes_A;Clostridia;Lachnospirales;Lachnospiraceae;14-2_10
>Bacteria;Firmicutes_A;Clostridia;Lachnospirales;Lachnospiraceae;14-2_11
>Bacteria;Firmicutes_A;Clostridia;Lachnospirales;Lachnospiraceae;14-2_12
>Bacteria;Firmicutes_A;Clostridia;Lachnospirales;Lachnospiraceae;14-2_13
>Bacteria;Firmicutes_A;Clostridia;Lachnospirales;Lachnospiraceae;14-2_14
>Bacteria;Firmicutes_A;Clostridia;Lachnospirales;Lachnospiraceae;14-2_15
>Bacteria;Firmicutes_A;Clostridia;Lachnospirales;Lachnospiraceae;14-2_16
```
```
>assignTaxonomy(seqs = seq[,c(58,60)],refFasta = "~/Downloads/dbs/GTDB_bac120_arc53_ssu_r207_Genus_renamed.fa",outputBootstraps = T,multithread = T)->tg_renamed

> unname(tg_renamed$tax)
     [,1]       [,2]           [,3]         [,4]             [,5]              [,6]     
[1,] "Bacteria" NA             NA           NA               NA                NA       
[2,] "Bacteria" "Firmicutes_A" "Clostridia" "Lachnospirales" "Lachnospiraceae" "14-2_10"

```
If I use this file I get the annotation of 14-2_10. I am just trying to figure out why this is happening. May be the  C_assign_taxonomy2 is not using the tax.mat.int and ref.to.genus is not working properly?

**Comment by benjjneb** [comment] 2023-02-23 02:09
This looks potentially i nteresting, but there is enough hidden setup here that I can't really tell for sure.

Can you put together a minimal example, e.g. two sequences and two reference files that produce this sort of discordant output? Something I could reproduce potentially.

**Comment by ramay** [comment] 2023-02-23 04:29
Great! 
I posted the dropbox link with the files with my first message but here it is again. 
https://www.dropbox.com/sh/8466h249g04jqyj/AAAAgnYO9ElX8R8qk81vN6tYa?dl=0

You will find the reference files in the dbs folder and seq_tab.rds object with two sequences I have used above.
Thanks for looking into this!

**Comment by benjjneb** [comment] 2023-02-24 14:38
Can you also add the `GTDB_bac120_arc53_ssu_r207_Genus_renamed.fa` file you generated? I don't see that in the Dropbox link, and seeing why that is giving a `14-2` as best hit instead of `FD2005` is where I would start.

**Comment by ramay** [comment] 2023-02-24 16:38
Done. I placed the file in the dbs folder in dropbox. 
Hena

**Comment by ramay** [comment] 2023-03-14 20:00
Hi, 
Did you get a chance to test this? 
Thanks!
Hena

**Comment by salix-d** [comment] 2023-03-16 22:03
I have similar results when using GTDB and when using SILVA. 
For species assignment, I thought it was normal as the assignSpecies function works differently than the assignTaxonomy one.

I'm not sure how I got to that conclusion (as in, I don't remember if I saw it in the tutorial or if it's from a discussion with my lab), but I thought doing assign to genus and then adding species was supposed to be more accurate than assignTaxonomy with the 'FullTaxo'.

For the other assignments I assumed it was about how the groups are when having different numbers of taxonomic ranks?
I even tried with a taxonomy file that only had assignment up to Order and tried 10 of the sequences that weren't classified to the order when using the FullTaxo file : 5 of them got an assignment to up to Order, 1 that didn't have a class now had one and 1 that had a phylum was now NA. 🤷‍♂️

**Comment by benjjneb** [comment] 2023-03-19 22:12
@ramay I have all the necessary files now, and have replicated the basic observation you described in https://github.com/benjjneb/dada2/issues/1699#issuecomment-1431743094. Thanks you for making such a good issue submission with a reproducible example.

This is on my list, but beyond that, no I haven't made progress. These days I can't promise a timeline on the issues that get into the "guts" as I once could.

**Comment by ramay** [comment] 2023-05-03 20:34
Hi @benjjneb have you had the chance to look at the code? I think the problem is in the C code. I have checked all the variables that are being passed on to the c function and seems like they have correct values. The problem is probably in how the c function is dealing with ref.to.genus and tax.mat.int. It has been ages since I have looked at  C code so not an expert at figuring it out. 
The reason why I am bothering you again is that this problem should get priority :) This problem will happen for anyone using SILVA(silva_nr99_v138.1_train_set.fa) or RDP (rdp_train_set_18.fa) dbs too as they both are at genus level with multiple sequences having the same header. This means ASVs are getting wrongly annotated like the example I shared with you. 
My quick fix right now is to make the taxonomy string unique by add a random number to it and removing at the end but would be great if you can please take a close look at  this issue.
Thanks!

**Comment by benjjneb** [comment] 2023-05-10 14:15
Thanks for bump @ramay 

I haven't yet, but agree this should be a priority. I've added a block of time on my calendar next week to start digging into this properly.

**Comment by benjjneb** [comment] 2023-05-18 20:58
OK, I think I understand what is going on. Perhaps unsatisfyingly, I believe this is the [naive Bayesian classifier](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC1950982/) method working as defined albeit perhaps not as one might expect.

The key thing is that in the naive Bayesian classifer, the query is not compared to the reference sequences, but to the reference "genera". More specifically, the kmer-profile of the query is compared to the aggregated kmer-profile constructed for each genus in the reference dataset (see "Genus-specific conditional probabilities" and "Naïve Bayesian assignment" sections of the paper for more details.

So, if we consider the second of your test query sequences, that is either `FD2005` (original GTDB) or `14-2_10` (renamed GTDB), what is happening is that the kmer-profile of the query is a better match to the kmer-profile of the FD2005 genus (which has a single reference sequence) than it is to the aggregated kmer-profile of the 14-2 genus (which has 16 reference sequences). But, when every sequence is forced into its own genus by the renaming, the query is a better match to the 10th reference sequence of 14-2 than it was to FD2005. This results in the switch in taxonomic assignment at the genus level.

This also explains why the assignments sometimes change between the genus-level and species-level GTDB references, in combination with the understanding that `assignTaxonomy` implements the naive Bayesian classifier using the terminal classification level in the reference database as the "genus" (in the sense of the description of the original nBC method) at which reference kmer profiles are aggregated for comparison.

What to do with this information? I'm not sure. As `assignTaxonomy` is not intended to be a new method, but just an implementation of the nBC, this isn't something we are going to change in how it operates. I would be interested to know in what fraction of queries you are seeing this sort of switching behavior. My suspicion is that it will also be concentrated in areas of the taxonomy with less clarity, or where there are clear non-phylogenetic anachronisms like the different names of `Shigella` and `E. coli`, despite them forming one coherent clade.

**Comment by benjjneb** [comment] 2023-05-18 21:52
Some quick example code replicating this behavior in a simulated reference with the query together with 10 random sequences in one genus X, while something close to the query is in the other genus Y.

```
library(ShortRead)
library(dada2)

setwd("~/Desktop/dada2_gtdb_issue/")
st <- readRDS("seqtab.rds")
query <- getSequences(st)[[2]]

rand.seq <- function(n) {
  paste0(sample(c("A","C","G","T"), n, replace=TRUE), collapse="")
}

set.seed(100)
refs <- c(query,
          rand.seq(1000),
          rand.seq(1000),
          rand.seq(1000),
          rand.seq(1000),
          rand.seq(1000),
          rand.seq(1000),
          rand.seq(1000),
          rand.seq(1000),
          rand.seq(1000),
          rand.seq(1000),
          paste0(substr(query,1,nchar(query)-50), rand.seq(50)))

names(refs) <- c(rep("K;P;C;O;F;GenusX;", 11), "K;P;C;O;F;GenusY")
refs.renamed <- refs
names(refs.renamed) <- c(paste(rep("K;P;C;O;F;GenusX", 11), seq(11), sep="_"), 
                         "K;P;C;O;F;GenusY")

nchar(refs) # All same, OK

fn.refs <- tempfile()
fn.refs.renamed <- tempfile()
writeFasta(refs, fn.refs)
writeFasta(refs.renamed, fn.refs.renamed)

unname(assignTaxonomy(query, fn.refs)) # Assigned to GenusY
unname(assignTaxonomy(query, fn.refs.renamed)) # Assigned to GenusX_1
```

**Closed** 2024-05-27 23:08 UTC
