### ISSUE TITLE
AssignTaxonomy retrieves different results, both with 100% bootstrapping

### ISSUE THREAD

**Issue by soluna1** [benjjneb/dada2#750] opened 2019-05-05 17:21 UTC
Hi,
This is an issue related to the results retrieved by the function AssignTaxonomy. As commented in similar issues, I agree that there are some randomness in the function as it is based on a probabilistic model, but I'm trying to understand why the same sequence is assigned to different genera when using different databases. The data are the following:
asv sequences: 130 bp of the v9 18s
database 1: pr2_version_4.11.1_dada2.fasta
database 2: custom-made database with only the v9 section of 18s

Both databases contain a very similar list of taxa, and in both the "problematic-genera" is included.
The code used to run the function "AssignTaxonomy" is the same, set.seed(42) in both cases, and the same parameters  (tax_db points to the database, pr2 or custom-made):
assignTaxonomy(seqtab, tax_db, taxLevels = c("Kingdom","Supergroup","Division","Class","Order","Family","Genus","Species"), multithread=T, tryRC=T, minBoot=80, outputBootstraps=T)

The problem:

The following asv_sequence "TCCTACCGATTGGATTGGCTGGTGAAGCGTTCGGATTGTGGGTTCGGAGCGGTTCGCCGTTCTGGGCTTGCGAGAAGTTCGTTAAACCCTCCTATCTAGAGGAAGGAGAAGTCGTAACAAGGTTTC"
is assigned to different genera in each case:

for pr2 --> Pseudoscourfieldia
for custom db--> Pycnococcus

in both cases the Bootstrap output is 100%.

This is not a big issue, as the family is the same for both genera, so I can go a level before. But my question is how I'll know when the 100% bootstrapping is really "true" or at least acceptable?

In this case, I would have expected that the 100% boostraping were retrieved at family level, not a genus level. Do you agree with this?

thanks in advance for your collaboration.
thanks benjjneb by paying attention to this issue.

**Comment by benjjneb** [comment] 2019-05-05 20:24
As a quick check, I BLASTed the provided sequences, and it is a 100% match to both *Pseudoscourfieldia marina* and *Pycnococcus provasolii*. So what we'd hope to get here is ambiguous assignments at the genus level (since it isn't resolvable on the basis of this sequence).

So, why are you getting these 100% bootstrap confidence assignments to different genera with the two reference dbs? If the sequences are present for both of those genus/species, and their id lines are properly formatted, that shouldn't be happening I don't think. In any case, the first place to look at is the reference files. Can you run the following shell command on both files, and report the output? It should return all entries in the fasta files that match this V9 sequence.

```
grep [asv_sequence] -B1 [ref-database.fasta]
```

Replace `[asv_sequence]` and `[ref-database.fasta]` with their appropriate values.

**Comment by soluna1** [comment] 2019-05-06 08:41
Hi benjjneb, 
Thanks for your answer. Yes, I had BLASTed the sequence after getting the results, and as you say the v9 section matches 100% both genera. That's why I expected to have the assignation only to family level, not to genus. 
Here it is the result of all sequences matching my v9-seq:
[output_both_db.txt](https://github.com/benjjneb/dada2/files/3147133/output_both_db.txt)

Thanks again for your interest.

**Comment by soluna1** [comment] 2019-05-06 12:30
Just trying to understand what is happening. Forgetting about the custom db, what seems odd to me it's why the algorithm selects one genus and not the other for this asv. I've checked if it selected the first option or the last option in the db, and not. 
At pr2 db there are 9 taxa IDs matching the asv, if I divide the asv length by the length of the whole 18s sequence for each option, I got the following:
1. 0.048 (Pycnococcaceae-clade1-sp)
2. 0.0708 (Pycnococcus_provasolii)
3. 0.0723 (Pseudoscourfieldia_marina)
4. 0.0724 (Pycnococcaceae_X_sp)
5. 0.0727 (Pycnococcus_provasolii)
6. 0.0726 (Pycnococcaceae-clade1-sp)
7. 0.0725 (Pseudoscourfieldia_marina)
8. 0.0726 (Pycnococcus_sp)
9. 0.0723 (Pycnococcus_provasolii)

So, the best matching in terms of number of bp would be seq. nº 5, instead the algorithm choses options 3 or 7, which have a lower matching. I would have expected to obtain a 100% bootstrapping at family level, or the genus with the higher number of matches. Am I wrong?

Thanks!!

**Comment by benjjneb** [comment] 2019-05-08 21:23
I may not have time to delve into this until next week. But before then, would you be willing to share your custom database so I can completley reproduce the results? My email is benjamin DOT j DOT callahan AT gmail DOT com

**Comment by benjjneb** [comment] 2019-05-14 21:23
Preliminary inspection indicates there is a bug, or at least a not working ideally, going on here.

The issue appears to be that when multiple exact matches exist in the dataset, with different taxonomic annotations, the first such annotation is repeatedly chosen. This is outside the scope of the original idea of the method which doesn't expect there to be lots of exact matches to the query sequences, but it should be handled better. Ideally a random draw of the exact matching sequences should be returned for each bootstrap replicate.

I haven't 100% confirmed this yet, but assuming this holds up I will work on an adjustment to the method that implements that better behavior in the presence of multiple exact matches.

**Comment by soluna1** [comment] 2019-05-15 16:48
Thanks for finding the time to pay attention to this. It is true that the fact that I'm using v9 region sequences, which are shorter than v4-v5, increases the probability of matching several db sequences. I've replicated the assignation 4 times with each db and I got always the same results, so as you said it should be that the algorithm is selecting one preferential option in each db, without considering the others. Happy to know that it could be handled. And thanks again for your feedback.

**Comment by KatjaKo** [comment] 2019-07-03 07:51
Hi, 
I have a similar problem as mentioned on the top of this page. 
Since I am also new to dada2 I would like to understand and find an explanation, why function assignTaxonomy is giving me different results. As mentioned earlier there is some randomness in the function and I am aware of them. 

My set of sequences belong to ITS region, therefore I am using UNITE database for taxonomic assignment. I ran function assignTaxonomy with default arguments, such as minBoot=50. But after several repetitions, I always got different results, for example: 
1) once the same sequence is assigned to species level, next time only to genus level or 
2) the same sequence is assigned up to the species level and next time that I run the same function all levels, except kingdom and phylum, are NA 
So far I am considering the genus level as the most accurate, but it is puzzling me since this issue is appearing also on other taxonomic levels. 

Additionally, I increased minBoot value, up to 100, but didn't help. 
Are there other parameters I have to consider or what else is causing this issue? 

Thanks in advance for your help @benjjneb and great tutorials regarding dada2!

**Comment by benjjneb** [comment] 2019-07-03 22:51
> 1. once the same sequence is assigned to species level, next time only to genus level or

As you noted above, there is randomness in how the "bootstrapping" part of the naive Bayesian classifier is performed. This most often will show up as you see here, where in one set of 100 bootstrap samples, enough are classified to the same species that a speceis classification is made, while next time they aren't and classification only happens to a broader level like genus. The [original paper by Wang et al. describing the naive Bayesian classifier algorithm](https://aem.asm.org/content/73/16/5261.short) (which `assignTaxonomy` reimplements) is a good reference for understanding what is going on there.

> 2. the same sequence is assigned up to the species level and next time that I run the same function all levels, except kingdom and phylum, are NA

This is more unusual. The potential explanation is that the closest matches in the refernece database to this ASV are two reference entries that are in different classes, and so sometimes >50 of the bootstraps hit the same entry and taxonomy is assigned all the way down to species, and sometimes <50 of the bootstraps do and taxonomy is only assigned down to the level those two reference entries agree agree (phylum).

That situation is pretty unusual in my experience, it might be worth BLAST-ing the sequence to see what is going on. It may be that the sequence is a chimera between two different real sequences?

**Comment by soluna1** [comment] 2019-08-12 07:01
Hi, 
Testing a little more on the different results obtained with AssignTaxonomy function, I found that the assignation seems to depend on the number of time a particular taxa is repeated in the database. 

So, using  EukDiv w2 v9 (TARA) reference database for 18s v9 illumina sequences, a particular asv was assigned to the most frequent taxa (c. closterium or B. paxillifer) depending on whether I put more copies of one or the other. Once all the options where balanced (no repetitions) the assignation was done to a higher taxonomic level, i.e. correct assignation.

This result points to the idea that the algorithm is choosing the most frequent option, not the first or the last, and when it can't "decide" because all options are equals (in frequency and percentage of matching) it goes a level before. So the solution will be to have only one copy of each sequence.

However, using pr2 (Vaulot 4.11, I've just notice that there is a new release) the same asv was correctly assigned to a higher taxonomic level in the first try, even if there are more "copies" of C. closterium than the rest of options (N. fonticola, B. paxillifer, C. fusifurmis, etc). I supposed that in the case of pr2 the proportion of nucleotides matching the reference sequence played a role in the assignation (it has the whole 18s), although I haven't checked this out yet.

It will be great if someone could confirm if similar results occur with other taxa groups, I mean if the assignation could depend on the "repetitions" of the reference database.

Thanks!!

**Closed** 2019-10-21 15:47 UTC
Labels: bug

**Comment by benjjneb** [comment] 2019-10-21 15:51
The `assignTaxonomy` code has been updated to randomly choose from the options when multiple best matches are found in the reference database. This solves this issue, as during the bootstrapping procedure the full range of taxonomic assignments amongst the best matches will be explored appropriately. Previously, the first best match was always chosen.

Use version 1.13.3 or later to get this new functionality. In my testing this has little or no impact on most 16S datasets, for which the reference sequences usually do include multiple identical sequences in them that are assigned different taxonomies.
