### ISSUE TITLE
Comparing results using different versions of DADA2?

### ISSUE THREAD

**Issue by janetw** [benjjneb/dada2#335] opened 2017-09-22 20:27 UTC
Hello,

This is not really an issue but a question about if it's a bad idea or an okay idea to compare results obtained using an older version of DADA2 and results obtained using the most recent version of DADA2.

I would like to be able to update to the newest version of DADA2 but have analyzed data done previously with an older version (1.2.2). We would like to be able to compare the results between a Miseq run done previously and a current MiSeq run. Usually we don't like to change things in the middle if we want to compare results.
Thoughts? Should I just continue to stick with 1.2.2 until we are completely done analyzing for this study? or would I be okay if I updated to the current version?

Thank you for any insight and suggestions.

Janet

**Comment by joey711** [comment] 2017-09-22 20:36
I would recommended re-running with the most recent DADA2 version on both runs (separately, of course, because of run-specific error rate differences).

I understand that you've already done some analysis, but the following things should be true:

- (1) the conclusions you want to communicate to others are robust to changes in DADA2 version.
- (2) you want to take advantage of improvements in the package since then, and you're still working, so why not spend your analysis effort on the best available?
- (3) you've done your analysis work in a **reproducible** way, so that it should be relatively painless to repeat the analysis steps you've already set up for the first dataset. If this is not the case, you should consider migrating into a reproducible workflow for many reasons, with flexibility to imbibe updates being one of them.

If you're in feverish haste that for some reason trumps quality and these considerations, you could "stick with" 1.2.2 I guess, but the benefit isn't clear to me, since you're going to have to put in some effort comparing the runs either way. This effort is most likely greater than running dada2 denoising.

**Comment by janetw** [comment] 2017-09-22 20:48
Thanks for the quick reply.

Yes, that makes sense. 
I've tried to do things in a reproducible way but I'm still learning and have a long way to go I think.
But I will find out I guess how well (or not) I did things.

In thinking of doing things in reproducible way, I am using R notebooks to document code and run the analysis and also run sessionInfo() at the end. Since I am still learning 'good practices' in doing things in a reproducible way, any other suggestions or resources that you would suggest I check into?

Thanks again,
Janet

**Comment by joey711** [comment] 2017-09-22 20:56
R notebooks is great. Hopefully that limits your repeated effort in this case. I think this exercise will help identify the gaps, which are up to you. 

For scholarly publication, my optimization criteria is that it should be not only possible to completely reproduce my results, but also as easy as possible. There are lots of tools around virtual machines an containers that support this for computing in general, especially helpful when the dependency requirements become large and/or esoteric.

I'll close this issue for now, but feel free to post back if something related comes up (or you want to brag about how easy it turned out to be because of your good reproducibility habits).

**Closed by joey711** 2017-09-22 20:56 UTC
