### ISSUE TITLE
Questions about removing chimeras with DADA2

### ISSUE THREAD

**Issue by LucianaGA** [benjjneb/dada2#900] opened 2019-11-26 17:43 UTC
Hi Ben,

I have done Miseq 150x2 runs to amplify the mitochondrial 12S gene (insert length: ca. 171 bp) and have been working on the Bioinformatic analysis with DADA2. I am having some problems when I try to remove chimeras. I am losing the majority of my reads and these reads are from the same and most abundant ASV:

                   Sam                 input       filtered   denoisedF   denoisedR    merged    nonchim

Ptrim_SWP1_2_paired   2121074    2095839   2007249     2053372      1980539     114209

This ASV corresponds to the most common species that I am expecting to detect from environmental samples. Could you please help me with this? Do you have any thoughts on how to solve this problem?

I greatly appreciate for any comments and/or help. I will be happy to provide more information about my data and analysis.

**Comment by benjjneb** [comment] 2019-11-26 17:59
Do your reads include primers on them? 
How variable is the length of this amplicon -- can it be shorter than 150 bps?

**Comment by LucianaGA** [comment] 2019-11-26 18:30
The amplicon size is 222 bps and my reads included the primers initially, but I ran the filterAndTrim function again to remove the primers with trimLeft=27 and I am getting similar results. I think I will try it again using trimLeft= c(27,24).

**Comment by benjjneb** [comment] 2019-11-27 14:59
Is it possible that any additional technical bases are added to your reads after the primer sequences? Does your library setup use "heterogeneity spacers", i.e. variable length pads to make the amplicons start at different positions in the sequencer?

The other possibility is that the biology of the mito 12S locus is just different, and that there are many recombinant alleles that truly exist and that are being removed as chimeras by the algorithm when they shouldn't be. That's hard to square with such an extreme amount of read removal, but it should be considered. Do you know much about how much recombinant diversity there is in this locus? Also, can you post the exact `removeBimeraDenovo` command you are running?

**Comment by LucianaGA** [comment] 2019-12-03 21:05
Thank you for your questions and comments! 

This is the command that I am running to remove chimeras:
seqtab<- removeBimeraDenovo(seqtab, method="consensus", multithread=TRUE, verbose=TRUE)

I think the answer for your both questions is "no", but I will double check about it. 

Thanks again!

**Comment by lafrue** [comment] 2019-12-13 10:02
I am also loosing quite a lot of reads ( i can keep constant about 75-89% of my raw reads through the whole dada2 pipeline, but after the chim check, I am only left with about 21% of my initial reads and I guess that's a quite low yield. I removed my primers before running dada2 with cutadapt and checked the fastq files. I am analyzing V3V4 region of 16s rDNA of bacteria, size of the region about 420bp with R1 R2 250bp paired end files. Everything works pretty fine except the chimcheck. any ideas? I guess recombinant alleles do not explain so many chimeras for a whole domain, or do they?

**Comment by benjjneb** [comment] 2019-12-14 16:52
Can you post the output of the following:

```
fnF <- "an_example_forward_reads.fastq"
drpF <- derepFastq(fnF)
dada2:::pfasta(getSequence(drpF)[1:20])
```

**Comment by lafrue** [comment] 2019-12-16 09:21
Hi Benjamin, the commndline outputs the following sequences
![getSequences](https://user-images.githubusercontent.com/55782737/70894204-d97fdd80-1fec-11ea-8012-8164f48d005f.png)

**Comment by benjjneb** [comment] 2019-12-16 13:56
Can you post it in text form, rather than as a screenshot image? I can't copy/paste the DNA strings from an image.

**Comment by lafrue** [comment] 2019-12-16 14:30
of course, sorry for the misunderstanding

dada2:::pfasta(getSequences(drpF)[1:20])
1
TGAGGAATATTGGTCAATGGACGCAAGTCTGAACCAGCCATGTCGCGTGCAGGATGACGGCCCTATGGGTTGTAAACTGCTTTTTTACAGGAATAAACGTTGCTACGTGTAGTGATTTGAATGTACTGTATGAATAAGGATCGGCTAACTCCGTGCCAGCAGCCGCGGTAATACGGAGGATTCGAGCGTTATCCGGATTTATTGGGTTTAAAGGGTCCGTAGGCGGTTCTTTAA
2
TGGGGAATATTGCGCAATGGGGGAAACCCTGACGCAGCAACGCCGCGTGAGTGATGAAGGTTTTCGGATCGTAAAGCTCTGTCTTCAGGGACGATAATGACGGTACCTGAGGAGGAAGCCACGGCTAACTACGTGCCAGCAGCCGCGGTAATACGTAGGTGGCAAGCGTTGTCCGGATTTACTGGGCGTAAAGAGTATGTAGGCGGATAATTAAGTCAGATGTGAAATACCCAG
3
TGGGGAATATTGCACAATGGAGGAAACTCTGATGCAGCAACGCCGCGTGGAGGATGACACTTTTCGGAGCGTAAACTCCTTTTATATAGGAAGATAATGACGGTACTATATGAATAAGCACCGGCTAACTCCGTGCCAGCAGCCGCGGTAATACGGAGGGTGCAAGCGTTACTCGGAATCACTGGGCGTAAAGAGCGTGTAGGCGGATTAATAAGTTGGGAGTGAAATCCTATG
4
TGGGGAATATTGCACAATGGGCGAAAGCCTGATGCAGCCATGCCGCGTGTATGAAGAAGGCCTTCGGGTTGTAAAGTACTTTCAGTTGTGAGGAAGGGGGTAACGTTAATAGCGTTATCTCTTGACGTTAGCAACAGAAGAAGCACCGGCTAACTCCGTGCCAGCAGCCGCGGTAATACGGAGGGTGCGAGCGTTAATCGGAATTACTGGGCGTAAAGCGCATGCAGGTGGTTC
5
TGAGGAATATTGGTCAATGGGCGCAAGCCTGAACCAGCCATGTCGCGTGCAGGATGACGGCCCTATGGGTTGTAAACTGCTTTTTTACAGGAATAATTGCAGATACGTGTATTTGTTTGAAGGTACTGTAAGAATAAGGATCGGCTAACTCCGTGCCAGCAGCCGCGGTAATACGGAGGATCCGAGCGTTATCCGGATTTATTGGGTTTAAAGGGTCCGTAGGCGGGCTGATAA
6
TGGGGAATATTGCGCAATGGGGGAAACCCTGACGCAGCAACGCCGCGTGAGCGATGAAGGTCTTCGGATTGTAAAGCTCTGTCTTTTGGGACGATAATGACGGTACCAAAGGAGGAAGCCACGGCTAACTACGTGCCAGCAGCCGCGGTAATACGTAGGTGGCAAGCGTTGTCCGGATTTACTGGGCGTAAAGAGTATGTAGGCGGATATTTAAGTCAGATGTGAAATACCCAG
7
TGGGGAATATTGCACAATGGGCGAAAGCCTGATGCAGCCATGCCGCGTGTATGAAGAAGGCCTTCGGGTTGTAAAGTACTTTCAGTTGTGAGGAAGGGTGTGTAGTTAATAGCTGCGCATCTTGACGTTAGCAACAGAAGAAGCACCGGCTAACTCCGTGCCAGCAGCCGCGGTAATACGGAGGGTGCGAGCGTTAATCGGAATTACTGGGCGTAAAGCGCATGCAGGTGGTTC
8
TTGGGAATATTGCGCAATGGGGGAAACCCTGACGCAGCAACGCCGCGTGCGGGATGAAGGCCTTAGGGTCGTAAACCGCTTTCAGCAGGGACGAAATAAGACTTTACCTGCATAAGAAGCTCCGGCTAAATACGTGCCAGCAGCCGCGGTAATACGTATGGAGCAAGCGTTATCCGGATTCATTGGGCGTAAAGCGCGCGTAGGCGGCCTTATAAGTCGAGTGTTAAACCCGAG
9
TGGGGGATATTGCACAATGGGCGAAAGCCTGATGCAGCAACGCCGCGTGAAGGAAGACGGTTTTCGGATTGTAAACTTCTATCAGCTGGGAAGAAAATGACTGTACCAGACTAAGAAGCCCCGGCTAACTACGTGCCAGCAGCCGCGGTAATACGTAGGGGGCAAGCGTTATCCGGATTTACTGGGTGTAAAGGGTACGTAGGCGGCTTACTAAGTCAGATGTGAAAGCCCGGA
10
TGGGGAATATTGCACAATGGGCGAAAGCCTGATGCAGCGACGCCGCGTGAGCGAAGAAGTATTTCGGTATGTAAAGCTCTATCAGCAGGGAAGATAATGACGGTACCTGACTAAGAAGCACCGGCTAAATACGTGCCAGCAGCCGCGGTAATACGTATGGTGCAAGCGTTATCCGGATTTACTGGGTGTAAAGGGAGCGTAGGTGGCAGAGTAAGTCTGATGTGAAAGCCCGGG
11
TGAGGAATATTGGTCAATGGACGCAAGTCTGAACCAGCCATGTCGCGTGCAGGATGACGGCCCTATGGGTTGTAAACTGCTTTTTTACAGGAATAAACGTTGCTACGTGTAGTGATTTGAATGTACTGTATGAATAAGGATCGGCTAACTCCGTGCCAGCAGCCGCGGTAATACGGAGGATTCGAGCGTTATCCGGATTTATTGGGTTTAAAGGGTCCGTAGGCGGGCTGATAA
12
TGGGGAATATTGCACAATGGAGGAAACTCTGATGCAGCAACGCCGCGTGGAGGATGACACTTTTCGGAGCGTAAACTCCTTTTATATAGGAAGATAATGACGGTACTATATGAATAAGCACCGGCTAACTCCGTGCCAGCAGCCGCGGTAATACGGAGGGTGCAAGCGTTACTCGGAATCACTGGGCGTAAAGAGCGTGTAGGCGGATAGATAAGTCAGAAGTGAAATCCAATA
13
TGGGGAATATTGCACAATGGAGGAAACTCTGATGCAGCAACGCCGCGTGGAGGATGACACTTTTCGGAGCGTAAACTCCTTTTATATAGGAAGATAATGACGGTACTATATGAATAAGCACCGGCTAACTCCGTGCCAGCAGCCGCGGTAATACGGAGGGTGCAAGCGTTACTCGGAATCACTGGGCGTAAAGAGCGTGTAGGCGGATAGATAAGTTTGAAGTGAAATCCAATG
14
TGGGGAATATTGCACAATGGGCGAAAGCCTGATGCAGCCATGCCGCGTGTATGAAGAAGGCCTTCGGGTTGTAAAGTACTTTCAGTTGTGAGGAAGGGTGTGTAGTTAATAGCTGCACATCTTGACGTTAGCAACAGAAGAAGCACCGGCTAACTCCGTGCCAGCAGCCGCGGTAATACGGAGGGTGCGAGCGTTAATCGGAATTACTGGGCGTAAAGCGCATGCAGGTGGTTC
15
TGGGGGATATTGCACAATGGGCGAAAGCCTGATGCAGCAACGCCGCGTGAAGGAAGACGGTTTTCGGATTGTAAACTTCTATCAGCTGGGAAGAAAATGACTGTACCAGACTAAGAAGCCCCGGCTAACTACGTGCCAGCAGCCGCGGTAATACGTAGGGGGCAAGCGTTATCCGGATTTACTGGGTGTAAAGGGTACGTAGGCGGCTGACTAAGTCAGATGTGAAAGCCCGGA
16
TGGGGGATATTGCACAATGGGCGAAAGCCTGATGCAGCAACGCCGCGTGAAGGAAGACGGTTTTCGGATTGTAAACTTCTATCAGCTGGGAAGAAAATGACTGTACCAGACTAAGAAGCCCCGGCTAACTACGTGCCAGCAGCCGCGGTAATACGTAGGGGGCAAGCGTTATCCGGATTTACTGGGTGTAAAGGGTACGTAGGCGGCTAACTAAGTCAGATGTGAAAGCCCGGA
17
TGGGGAATATTGCGCAATGGGGGAAACCCTGACGCAGCAACGCCGCGTGAGTGATGAAGGTTTTCGGATCGTAAAGCTCTGTCTTCAGGGACGATAATGACGGTACCTGAGGAGGAAGCCACGGCTAACTACGTGCCAGCAGCCGCGGTAATACGTAGGTGGCAAGCGTTGTCCGGATTTACTGGGCGTAAAGAGTATGTAGGCGGATATTTAAGTCAGATGTGAAATACCCAG
18
TGAGGAATATTGGTCAATGGACGCAAGTCTGAACCAGCCATGTCGCGTGCAGGATGACGGCCCTATGGGTTGTAAACTGCTTTTTTACAGGAATAAACGTTGCTACGTGTAGTGATTTGAATGTACTGTATGAATAAGGATCGGCTAACTCCGTGCCAGCAGCCGCGGTAATACGGAGGATCCGAGCGTTATCCGGATTTATTGGGTTTAAAGGGTCCGTAGGCGGGCTGATAA
19
TGGGGAATATTGCGCAATGGGGGAAACCCTGACGCAGCAACGCCGCGTGAGCGATGAAGGTCTTCGGATTGTAAAGCTCTGTCTTTTGGGACGATAATGACGGTACCAAAGGAGGAAGCCACGGCTAACTACGTGCCAGCAGCCGCGGTAATACGTAGGTGGCAAGCGTTGTCCGGATTTACTGGGCGTAAAGAGTATGTAGGCGGATAATTAAGTCAGATGTGAAATACCCAG
20
TGGGGAATATTGCACAATGGGCGCAAGCCTGATGCAGCCATGCCGCGTGTATGAAGAAGGCCTTCGGGTTGTAAAGTACTTTCAGTCGTGAGGAAGGTGGTGTTGTTAATAGCAGCATCATTTGACGTTAGCGACAGAAGAAGCACCGGCTAACTCCGTGCCAGCAGCCGCGGTAATACGGAGGGTGCGAGCGTTAATCGGAATTACTGGGCGTAAAGCGCATGCAGGTGGTTC

**Comment by benjjneb** [comment] 2019-12-16 15:08
The issue here appears to be that while you removed the primers at the start of the reads with `trimLeft`, you did not remove the primers that appear at the ends of the reads, i.e. the opposite primer (the REV primer on the forward reads and vice versa). This is an issue because your reads (according to the output above) are longer than your amplicon, and these unremoved primers are what is causing the chimeras issues.

Can you confirm that you are not working with 2x150 reads as originally stated, but (probably?) with 2x250 data?

I do not know about 12S, but as long as the biological length variation in the locus is limited, you can easily solve this problem by truncating the forward and reverse reads before they reach the opposite primer with `truncLen`. Alternatively you can use an external primer removal program, but you need to be sure you remove both primers from each read, see the ITS tutorial for an example: https://benjjneb.github.io/dada2/ITS_workflow.html

**Comment by lafrue** [comment] 2019-12-17 15:45
Hi, I now applied the workflow you mentioned above on my data and both removed primers in forward and in rev-comp direction as in your example (my samples had same distribution of primer in files as the example data had). 
Everything worked well, except the output files generated with cutadapt all consist of not more than 100000 sequences/file (counted with terminal command grep -c "^+$" *fastq)
I could not find any parameter both in R and cutadapt documentation that may limit the printed sequences into the new files, do you have any idea? 
Further, although all spurious primers in the amplicons are now hopefully removed, the percentage of chimeras is still about 79% (sum(seqtab_nochim)/sum(seqtab) = 0,212837)

You are right, I  am not doing this with ITS data, but with 16S paired end 250bp long R1 and R2 reads. 
>  I am analyzing V3V4 region of 16s rDNA of bacteria, size of the region about 420bp with R1 R2 250bp paired end files. Everything works pretty fine except the chimcheck. any ideas?

**Comment by benjjneb** [comment] 2019-12-17 21:04
Ah, I was confused, I didn't catch that you had joined into this other thread, probably because your handle and the OP both start with the letter L.

Can you provide the exact command you are running to remove chimeras?

Can you also test the following: `removeBimeraDenovo(..., minFoldParentOverAbundance=4)` and also `8` and `16` and report the fraction identified as chimeras?

**Comment by lafrue** [comment] 2019-12-18 21:45
this is the command for chimremoval: 
seqtabAfter <- removeBimeraDenovo(seqtabBefore, method = "consensus", multithread=ncpus, verbose=TRUE)
and with the different parameters of minFoldParent i get the following output (I hope this is what you were talking about the fraction of chimeras, if not, let me know and I will provide further information)
chim_perc_original <- sum(seqtabAfter)/sum(seqtabBefore)
chim_perc_4 <- sum(seqtabAfter4)/sum(seqtabBefore)
chim_perc_8 <- sum(seqtabAfter8)/sum(seqtabBefore)
chim_perc_16 <- sum(seqtabAfter16)/sum(seqtabBefore)
[1] 0.2897197
[1] 0.4237747
[1] 0.5402597
[1] 0.6755989
We also did a blastn analysis with some random 50 sequences which were removed as "chimeras" and an alignment: sequences identified as "chimeras" have an insertion between 85 and 110 bp, and the "non-chims“ a deletion (query coverage of megablast was almost 100% for all sequences to non-chim database sequences and assigned organisms.

**Comment by benjjneb** [comment] 2019-12-23 22:18
> We also did a blastn analysis with some random 50 sequences which were removed as "chimeras" and an alignment: sequences identified as "chimeras" have an insertion between 85 and 110 bp, and the "non-chims“ a deletion (query coverage of megablast was almost 100% for all sequences to non-chim database sequences and assigned organisms.

!!

Can you post the sequences you analyzed? If I'm reading this correctly, this is something I've never seen before. At this point it might also be useful if you could share even just a single sample of your data with me, so I can try to reproduce the results you are seeing on my end.

**Comment by LucianaGA** [comment] 2020-01-10 16:35
Hi, 

I am still working on my data (Miseq 150x2 runs to amplify the mitochondrial 12S rRNA gene) to remove chimeras. I used the Nextera adapters and heterogeneity spacers for the library setup. I have some questions related to the results after merging reads and removing chimeras.

After merging the reads I got this length distribution in my seqtab table:

0 152 170 173 192 205 209 210 211 214 215 216 218 219 229 232 233 257 260 267 276 278 279 
1     1    1    4    79     2     3      1     1     2     3     4     3     9    12     1      4     3     2      2     1     2     3 

What does "0" length mean? When I removed chimeras after this step I lost a lot of reads.

seqtab.nochim <- removeBimeraDenovo(seqtab, method="consensus", multithread=TRUE, verbose=TRUE)
Identified 95 bimeras out of 144 input sequences

sum(seqtab.nochim)/sum(seqtab)
[1] 0.04595501

dim(seqtab.nochim)
[1]  1 49

head(track)
                                                    input      filtered     denoisedF denoisedR      merged   nonchim
Ptrim_SWP1_1_paired        2808933  2745746   2695628       2705930      2665868  122510

When I removed this "0"  length, selecting a specific length, I got different results, after removing chimeras, but I cannot see the dimension of the table and either visualize the results:

seqtab2 <- seqtab[,nchar(colnames(seqtab)) %in% 152:229]

seqtab.nochim2 <- removeBimeraDenovo(seqtab2, method="consensus", multithread=TRUE, verbose=TRUE)
Identified 73 bimeras out of 125 input sequences.

sum(seqtab.nochim2)/sum(seqtab2)
[1] 0.9941439

**dim(seqtab.nochim2)
NULL**

track2 <- cbind(out, getN(dadaFs), getN(dadaRs), getN(mergers_20_1), rowSums(seqtab.nochim2))

**Duplicate sequences detected and merged.
Error in rowSums(seqtab.nochim2) : 
  'x' must be an array of at least two dimensions**

I visualized the table in Excel using “write.table(seqtab.nochim2,file=" ", sep= "\t")” and there is a “x” in the first row.

I used these parameters for filterAndTrim:

out <- filterAndTrim(fnFs, filtFs, fnRs, filtRs, maxN=0, maxEE=3, truncQ=2, rm.phix=TRUE,
              compress=TRUE, multithread=TRUE)

I also ran other parameters to remove primers but I am still having the same problem:

out2 <- filterAndTrim(fnFs, filtFs, fnRs, filtRs, trimLeft = 24, trimRight = 27, 
maxN=0, maxEE=2, truncQ=2, rm.phix=TRUE, compress=TRUE, multithread=TRUE)

out3<- filterAndTrim(fnFs, filtFs, fnRs, filtRs, truncLen= 140, maxN=0, maxEE=2, truncQ=2, rm.phix=TRUE

Thank you!

**Comment by benjjneb** [comment] 2020-01-10 17:58
@LucianaGA 

> I used the Nextera adapters and heterogeneity spacers for the library setup.

If you used heterogeneity spacers, you must use an external program to remove those spacer sequences (and possibly preceding primer sequence as well) prior to utilizing DADA2.

The artificial sequence variation introduced by heterogeneity spacers interferes with the DADA2 algorithm at both the denoising and chimera removal steps. Typically, heterogeneticy spacres are not adequately addressed by the normal `trimLeft` approach of removing a fixed number of bases at the start of the reads, because they vary in their number of bases.

**Comment by LucianaGA** [comment] 2020-01-14 21:50
Thank you for your explanation!

**Comment by lafrue** [comment] 2020-01-20 12:02
> > We also did a blastn analysis with some random 50 sequences which were removed as "chimeras" and an alignment: sequences identified as "chimeras" have an insertion between 85 and 110 bp, and the "non-chims“ a deletion (query coverage of megablast was almost 100% for all sequences to non-chim database sequences and assigned organisms.
> 
> !!
> 
> Can you post the sequences you analyzed? If I'm reading this correctly, this is something I've never seen before. At this point it might also be useful if you could share even just a single sample of your data with me, so I can try to reproduce the results you are seeing on my end.

Hi, sorry for the late reply, been on a long vacation after the holidays. Attached the files for the 50 sequences from my last comment. 
[chimCheck50Randoms.txt](https://github.com/benjjneb/dada2/files/4086010/chimCheck50Randoms.txt)

I will email you the fastq files, since I can't drag them here.

Thank you !

**Comment by lafrue** [comment] 2020-01-20 12:21
Anhänge verfügbar bis 19.02.2020
Please find the attached R1 and R2 files for two of my samples of my data for the very high sequences loss during chimcheck. 
Best, Larissa Frühe

—————————————————
Larissa Frühe
Zum Laden klicken
 <https://www.icloud.com/attachment/?u=https%3A%2F%2Fcvws.icloud-content.com%2FB%2FAQnAAPCIIwsYHhS38Yas5NbkLtMgASJeYof_R5bM9UJUmlRqMT4Cheyf%2F%24%7Bf%7D%3Fo%3DAnluGYI3H4nSDqwpXaDYocJR_W4ZWHjzGjTwfkc9Vfw1%26v%3D1%26x%3D3%26a%3DCAogchh9c35q-Ge1zkZCYgxylWnr-ar0KDsOgp24YkfmAtYSJxDs4piX_C0Y7PKT64UuIgEAKggByAD_Fr_hLVIE5C7TIFoEAoXsnw%26e%3D1582114863%26k%3D%24%7Buk%7D%26fl%3D%26r%3D25D5B42F-97B7-4F10-A875-33225FE2CA95-1%26ckc%3Dcom.apple.largeattachment%26ckz%3D574E3D81-5882-4148-A5A7-9301D85CF005%26p%3D25%26s%3Dj2okrpQKE_AOK-WMiJS2PHWnbPk&uk=xS7jWBLnlkAVhFFydFZbJw&f=70m-NW-2_S28_L001_R1_001.fastq&sz=74918764>70m-NW-2_S28_L001_R1_001.fastq
74,9 MB
Zum Laden klicken
 <https://www.icloud.com/attachment/?u=https%3A%2F%2Fcvws.icloud-content.com%2FB%2FAbjiHw3T8TbCwO_a21O3mtQb-6iZAYw4W0Xm_8YbLtzJTUXp4bzwgl3i%2F%24%7Bf%7D%3Fo%3DAl0DN0H1NYagM3TSXWoRn8ok3qAlADpc1AWSI9YACvqh%26v%3D1%26x%3D3%26a%3DCAogeTlNkz2HAFWcICnINDJLN-usQN2XhJkIw0zlsnq-WgsSJxDQ4JiX_C0Y0PCT64UuIgEAKggByAD_ftWMr1IEG_uomVoE8IJd4g%26e%3D1582114863%26k%3D%24%7Buk%7D%26fl%3D%26r%3D8D339C7C-1459-4E33-B92D-8A29D5A8F00E-1%26ckc%3Dcom.apple.largeattachment%26ckz%3D574E3D81-5882-4148-A5A7-9301D85CF005%26p%3D25%26s%3DOCcoNNvqX_jCpX3XHR1pERlwLJE&uk=pzyrE1EvSLZyJqv7xFM83Q&f=REF-2-1_S31_L001_R1_001.fastq&sz=66462979>REF-2-1_S31_L001_R1_001.fastq
66,5 MB
Zum Laden klicken
 <https://www.icloud.com/attachment/?u=https%3A%2F%2Fcvws.icloud-content.com%2FB%2FAVGwQ_MyAJxvvQmsXZl-Xxv35oJwAYErUPOSF5tTpa1tmsem9Z-sfZ4q%2F%24%7Bf%7D%3Fo%3DAsizxoPvWTjIZCLHRs2wnaapTO41wdRPaL0t-0ngflkn%26v%3D1%26x%3D3%26a%3DCAogJbtplEBdIZZJllwuMQFiekjeuoQ9PlkebAHfQJY8L5MSJxDZ4ZiX_C0Y2fGT64UuIgEAKggByAD_MIqGfVIE9-aCcFoErH2eKg%26e%3D1582114863%26k%3D%24%7Buk%7D%26fl%3D%26r%3D107C2BB7-CA1A-4C0E-841E-EABE6C046506-1%26ckc%3Dcom.apple.largeattachment%26ckz%3D574E3D81-5882-4148-A5A7-9301D85CF005%26p%3D25%26s%3D3EwBa7-DVOpRzWvLNVVRR8RO9zc&uk=g5-hQ4e4eB11r6vPRZmLQA&f=REF-2-1_S31_L001_R2_001.fastq&sz=66462979>REF-2-1_S31_L001_R2_001.fastq
66,5 MB
Zum Laden klicken
 <https://www.icloud.com/attachment/?u=https%3A%2F%2Fcvws.icloud-content.com%2FB%2FAVCm3GrShvcsM7-kXsPxJZ4VWMRpAZk3aT-IKutfHJOFb0cXO1YGIbE4%2F%24%7Bf%7D%3Fo%3DAlpf13WkLJP1p1o_0IP236eA6kwgEA7gaANkd4ejzEHT%26v%3D1%26x%3D3%26a%3DCAog5UwMDxszbGW2GpN0DM7F79vEPCsde_HPeYFc5iBUTSsSJxDh55iX_C0Y4feT64UuIgEAKggByAD_Vb8fJ1IEFVjEaVoEBiGxOA%26e%3D1582114864%26k%3D%24%7Buk%7D%26fl%3D%26r%3D5E52FA88-093B-4BF4-B88E-EB1FAE91FBEF-1%26ckc%3Dcom.apple.largeattachment%26ckz%3D574E3D81-5882-4148-A5A7-9301D85CF005%26p%3D25%26s%3D4L33Gt4TuwUhXEks_JYNg-kKpHA&uk=oVNZo8P-hr7T9Q5fRMG_3w&f=70m-NW-2_S28_L001_R2_001.fastq&sz=74918764>70m-NW-2_S28_L001_R2_001.fastq
74,9 MB
University of Kaiserslautern
Faculty of Biology
Department of Ecology
Erwin-Schroedinger Straße 14, Room 14/260
67663 Kaiserslautern
Germany

email: fruehe@rhrk.uni-kl.de <mailto:fruehe@rhrk.uni-kl.de>
phone: +49 (0) 631 205 3623
https://https://www.bio.uni-kl.de/ecology/team/ag-stoeck/larissa-fruehe/ <https://www.bio.uni-kl.de/ecology/team/ag-stoeck/larissa-fruehe/>

**Comment by benjjneb** [comment] 2020-01-22 20:55
Thanks, was able to download the files. I'll take a look, but may take me a few days to have time to dig into this in more detail.

But if you don't hear from me for too long, please re-ping the thread.

**Comment by benjjneb** [comment] 2020-01-31 01:40
@lafrue  Can you post a minimal workflow that reproduces the relevang behavior on the files you provided? 

Sorry but I am getting confused, in large part because of the mixture of posts between you and the other poster on this thread (note to self: best to separate such threads into their own topics in the future)

**Comment by lafrue** [comment] 2020-01-31 10:15
Format got disrupted while coping on GitHub, here is the exact workflow we used with the example data I sent you in the last email. 
Thanks a million for taking your time to solve this with me ! 

All the best and a nice weekend, Larissa

—————————————————
Larissa Frühe

University of Kaiserslautern
Faculty of Biology
Department of Ecology
Erwin-Schroedinger Straße 14, Room 14/260
67663 Kaiserslautern
Germany

email: fruehe@rhrk.uni-kl.de
phone: +49 (0) 631 205 3623
https://https://www.bio.uni-kl.de/ecology/team/ag-stoeck/larissa-fruehe/

**Comment by benjjneb** [comment] 2020-01-31 21:58
@lafrue I don't see any R commands or a workflow in your post?

**Comment by lafrue** [comment] 2020-02-02 21:05
> @lafrue I don't see any R commands or a workflow in your post?

[dada_seqit_d_u.txt](https://github.com/benjjneb/dada2/files/4145320/dada_seqit_d_u.txt)

**Comment by benjjneb** [comment] 2020-02-03 20:27
@lafrue After reviewing the example data, I think there probably is a high rate of chimeras in the data, but that also some inter-species variants may be getting errantly flagged as chimeras. This is more common in taxa like Vibrio which have lots of 16S gene copies (~10 on average) and in which there are many closely related "species".

What I'd recommend is to increase the stringency of chimera removal by increasing the `minFoldParentOverAbundance` parameter. This sets how much more abundant a putative "parent" sequence must be to be evidence for flagging a "child" sequence as chimeric. You should also be using the "consensus" method, as that helps with this issue as well. So something like this...

```
st <- removeBimeraDenovo(myseqtab, minFoldParentOverAbundance=8, method="consensus", multi=TRUE)
```

**Comment by lafrue** [comment] 2020-02-07 12:05
That solved the problem, I increased the reads after the chimcheck by 50% !! 
Thank you !

**Closed** 2020-04-03 14:11 UTC
