### ISSUE TITLE
Error in filterAndTrim

### ISSUE THREAD

**Issue by yannmean** [benjjneb/dada2#285] opened 2017-07-19 06:19 UTC
Hi, there!

I am re-running my codes (which used to work without any issues) using the same dataset, same directory. However, when I was using filterAndTrim function, an error popped out as following: 

scheduled core 1 encountered error in user code, all values of the job will be affected
Error in `colnames<-`(`*tmp*`, value = basename(fwd)) : attempt to set 'colnames' on an object with less than two dimensions
  
My codes are provided below:
Sort forward and reverse reads, make sure they are in the same order, using the same naming convention.

```{r sort forward and reverse reads}
fnFs <- sort(list.files(path, pattern = "_R1_001.fastq"))
fnRs <- sort(list.files(path, pattern = "_R2_001.fastq"))
```

Extract sample names, and specify the full path to the fnFs and fnRs

```{r sample names}
sample.names <- sapply(strsplit(fnFs, "_"), `[`, 1)
fnFs <- file.path(path, fnFs)
fnRs <- file.path(path, fnRs)
```

Plot out quality profiles of forward and reverse reads.

```{r quality}
plotQualityProfile(fnFs[1:2])
plotQualityProfile(fnRs[1:2]) ## what the f**k is wrong with it..
```

Filtering and trimming the raw data based on the quality profile. 

```{r filter}
filt_path <- file.path(path, "filtered")
filtFs <- file.path(filt_path, paste0(sample.names, "_F_filt.fastq.gz"))
filtRs <- file.path(filt_path, paste0(sample.names, "_R_filt.fastq.gz"))
out <- filterAndTrim(fnFs, filtFs, fnRs, filtRs, truncLen = c(150, 150), 
                     maxN = 0, maxEE = c(2,2), truncQ = 2, rm.phix = TRUE, 
                     compress = TRUE, multithread = TRUE)
head(out)
```

Operating System is OS X El Capitan 10.11..6
R version is 3.4.1 Single Candle
Dada2 version is 1.4

Thank you very much for your time and attention. 
Yann

**Comment by benjjneb** [comment] 2017-07-19 12:08
Hi Yann,
This error message with `filterAndTrim` came up before, and was related to an issue with an older version of the `ShortRead` package: https://github.com/benjjneb/dada2/issues/263

Can you check if updating your Bioconductor installation (which includes ShortRead) fixes the problem? That may fix both your errors/warnings actually.

**Comment by yannmean** [comment] 2017-07-19 18:19
Hi, Ben,

Thank you for your kind response. 

I used the following command line to recompile installed packages:
```{r recompile}
source("https://bioconductor.org/biocLite.R")
pkgs <- rownames(installed.packages())
biocLite(pkgs, type="source")
```
It seems everything was reinstalled, except igraph package is still version 1.0.1  instead of 1.1.1.
I checked the version of the ShortRead package, which is 1.34. 

I reran all the codes including the plotQualityProfile and filterAndTrim. The same errors from both command lines both reoccured. I also noticed that these errors occured after I updated my OS system. So I reinstalled R and everything. Still doesn't help. But I don't know whether these system update and errors are just coincident or actually correlated.. 

Thank you,

Yann

**Comment by benjjneb** [comment] 2017-07-19 18:25
Can you try running `filterAndTrim` with `multithread=FALSE` and report back the output? A test run on a couple of samples would be fine.

**Comment by yannmean** [comment] 2017-07-19 18:55
Hi, Ben, 

Yes, I have just tried multithread = FALSE. 
The output is the following error:
```{r}
Error in add(bin) : internal: buf != <newline> 
```

**Comment by benjjneb** [comment] 2017-07-19 19:03
Hm... given the problem with `plotQualitityProfile` on the reverse files, perhaps those files are ill-formed? Could you inspect the top of one of those files to make sure it looks as expected?

**Comment by yannmean** [comment] 2017-07-19 19:07
Hi, Ben, 

Yes, that was my original concern as well. I actually opened several reverse files, it looks nothing suspicious. I used the same files and the dada2 package for analysis a couple of months ago, it worked well. And I didn't change or edit anything in the original raw data file..

**Comment by benjjneb** [comment] 2017-07-19 19:10
Could you share the F/R files from a sample or two that are giving this error? It will help to narrow it down if I can replicate it (or not) on my own machine.

**Comment by yannmean** [comment] 2017-07-19 19:14
Yes, I have responded via email. The attachment file size is around 30 MB with 3 samples' F/R files, 6 files in total. 

Thank you!

**Comment by benjjneb** [comment] 2017-07-20 14:12
Hi Yann,
FYI I haven't received anything via email as of right now.

**Comment by yannmean** [comment] 2017-07-20 18:42
Hi, Ben!
I think maybe it's due to the size of the attachment. It was too big. I have just resent the data. This time I only sent 2 samples' F/R files, 4 files in total, size is around 20MB. 

Thank you very much for following up with me! 

Take care, 
Yan

**Comment by benjjneb** [comment] 2017-07-20 23:58
So when I run the exact code you posted, it works as expected on the two samples-worth of data you sent me...

Can you post the full output of `sessionInfo()` on your machine? And how are you running these commands - is it via an interactive session? Rstudio? Or via an Rscript call?

**Comment by benjjneb** [comment] 2017-07-21 00:09
So the one previous time an error like this showed up it had to do with misformatting of the fastq file: https://github.com/benjjneb/dada2/issues/153

This message isn't quite the same, I wonder if their could be a newline issue cropping up (i.e. newline vs carriage return) in one of the files.

Can you confirm that you are getting this error from the exact files you emailed me? (F1604426 and F1604427)

ps: These sequences have an extremely uniform quality score distribution. What instrument is generating this data?

**Comment by fanli-gcb** [comment] 2017-07-21 06:59
> ps: These sequences have an extremely uniform quality score distribution. What instrument is generating this data?

I recently got some MiniSeq data that had an oddly uniform quality distribution as well. Am still not sure if that's the platform, or an error on my end.

**Comment by yannmean** [comment] 2017-07-21 07:09
Hi, Ben, 

Sorry for my late response! 
After you mentioned the data quality for the second time, I actually re-decompressed the original files. This time it works well again. I think there might be some data corruption. However, I was only copy-pasting the data from one folder to another..really didn't know what went wrong during this process. Now everything works well. Thank you again for all your help! Really appreciate it!

**Comment by yannmean** [comment] 2017-07-21 07:11
Hi, fanli-gcb, 

My data is also from MiniSeq. My quality distribution falls within gray box with a score around 40. MiniSeq data only has 150 bp per read. So the distribution might look a bit stretched on the graph.

Yann

**Comment by benjjneb** [comment] 2017-07-21 13:18
Glad its working. I think now with 2/2 cases of `Error in add(bin) : ...` being caused by corrupted unzipped files I'll know exactly what to recommend next time!

I may have to test out some MiniSeq data at some point. I had heard in some newer instruments Illumina was moving to a reduced Q score set where they only used like 8 values, and it looks like that is the case there.

**Closed by benjjneb** 2017-07-21 13:18 UTC
