### ISSUE TITLE
dada2 fails to compile on 64 bit windows

### ISSUE THREAD

**Issue by seedpcseed** [benjjneb/dada2#43] opened 2015-10-03 01:07 UTC
I have tried several times to install dada2 into standalone R V3.1 or in RStudio, each on a Windows10 machine (although it also failed on a Windows 8 machine).  I appear to have all the dependencies installed but have a failure during the compilation.  

Here I am showing only the last part of the compilation where it appears things fail:

C:/Users/patcseed/Documents/R/win-library/3.1/Rcpp/include/Rcpp/internal/Exporter.h:31:31: error: invalid conversion from 'SEXP' to 'long long unsigned int' [-fpermissive]
make: *** [RcppExports.o] Error 1
Warning: running command 'make -f "C:/PROGRA~1/R/R-3.1.3/etc/x64/Makeconf" -f "C:/PROGRA~1/R/R-3.1.3/share/make/winshlib.mk" SHLIB_LDFLAGS='$(SHLIB_CXXLDFLAGS)' SHLIB_LD='$(SHLIB_CXXLD)' SHLIB="dada2.dll" WIN=64 TCLBIN=64 OBJECTS="RcppExports.o Rmain.o cluster.o error.o evaluate.o misc.o nwalign_endsfree.o pval.o strmap.o"' had status 2
ERROR: compilation failed for package 'dada2'
* removing 'C:/Users/patcseed/Documents/R/win-library/3.1/dada2'
Error: Command failed (1)

I do not see this issue posted elsewhere.

Thank you.

**Comment by benjjneb** [comment] 2015-10-03 06:46
Yes, unfortunately this is a known issue (thanks for posting though, it should be up here) that is caused by differences in how the linux/osx compilers and the windows compilers are treating 64 bit integers. I think there might be a very simple fix (possibly just adding a windows compiler flag) but I need to arrange a windows test environment for myself to clear it up.

Partly for my own records, these links discuss this issue:

http://lists.r-forge.r-project.org/pipermail/rcpp-devel/2012-July/004009.html
http://stackoverflow.com/questions/8931123/return-wrap-of-size-t-in-rcpp
http://lists.r-forge.r-project.org/pipermail/rcpp-devel/2013-September/006434.html

**Comment by seedpcseed** [comment] 2015-10-03 16:31
Thanks for the reply. I look forward to your solution to evaluate this tool.
Pat

**Comment by benjjneb** [comment] 2015-10-11 11:45
Not fixed yet, but tested today on 32-bit Windows Vista machine: Compiles and runs fine.

The compilation issue appear to be specific to 64-bit Windows.

**Comment by seedpcseed** [comment] 2015-10-11 12:05
Thanks for the update. Any idea on fixing the 64 bit problem?

**Comment by benjjneb** [comment] 2015-10-11 20:39
I just got the package building on Windows 7 (64 bit).
Easy fix once I figured out what was happening, just had to replace the size_t C variables that were interfacing with R numerics/integers with unsigned ints.

Don't have a Windows 8 or 10 machine to test, but I think today's update should allow it to compile fine on those as well! *fingers crossed*
Leaving open for now until confirmation that it does work for at least one other person.

**Comment by benjjneb** [comment] 2015-10-20 06:50
Hi Pat,
Was wondering if dada2 is compiling for you now? Will close this issue if so.

**Comment by seedpcseed** [comment] 2015-10-22 20:58
Hi Ben,
Terrific work! Compiles fully now on Windows10.  I have done some very
basic calls to make sure it fires up properly. All seems well after library
loading. I won't have a chance for a few days to do more but expect it to
work as you intended.

Thanks again
Pat

**Comment by benjjneb** [comment] 2015-10-23 05:45
Great. Closing this for now then, but reopen if new issues crop up.

**Closed by benjjneb** 2015-10-23 05:45 UTC

**Comment by seedpcseed** [comment] 2015-10-25 21:37
I can post this on the git site but am wondering if you have
recommendations for handling the miseq data to run through dada2.

I am well versed in taking our 2x250 PE runs through pairing,
demultiplexing, filtering etc.

Strangely my problem here is taking the R1, R2, and index and
demultiplexing but keeping the R1 and R2 completely matched. I'm finding
that most tools seem to occasionally miscall a barcode if done separately
on the R1 and R2 files. SO by the time I demultiplex, I end up with fastq
files for R

**Comment by seedpcseed** [comment] 2015-10-25 21:40
I can post this on the git site but am wondering if you have
recommendations for handling the miseq data to run throughdada2.

I am well versed in taking our 2x250 PE runs through pairing,
demultiplexing, filtering etc.

Strangely my problem here is taking the R1, R2, and index and
demultiplexing but keeping the R1 and R2 completely matched. I'm finding
that most tools seem to occasionally miscall a barcode if done separately
on the R1 and R2 files. SO by the time I demultiplex, I end up with fastq
files for R1 and R2 that are not complete matched. Close but not quite.
This is despite NO filtering prior to bringing the files in to R for dada2.


I scripted something in python as a "check" for synchrony but am finding it
is too slow considering I will often have 12+ seq runs with ~samples.

Suggestions? Again, trying to get from multiplexed R1, R2, and indexed into
1:1 fastq R1 and R2 to each sample.
Thanks
Pat

**Comment by benjjneb** [comment] 2015-10-31 06:37
Hi Pat,
This is a different problem, so I am reposting your comment as a new issue. See the answer I posted at https://github.com/benjjneb/dada2/issues/46
