### ISSUE TITLE
merge not working(?) no taxonomy assigned

### ISSUE THREAD

**Issue by lmsroo** [benjjneb/dada2#203] opened 2017-03-08 03:47 UTC
Hi, I've run through the tutorial and it works great. Using the same code that worked with the tutorial data I tried my own 16S sequencing data (n=6) and something seems wrong at the merger step.  This is what the code and output looks like:

> mergers <- mergePairs(dadaFs, derepFs, dadaRs, derepRs, verbose=TRUE)
0 paired-reads (in 0 unique pairings) successfully merged out of 45416 (in 9038 pairings) input.
2 paired-reads (in 1 unique pairings) successfully merged out of 35799 (in 9458 pairings) input.
4 paired-reads (in 2 unique pairings) successfully merged out of 45099 (in 13755 pairings) input.
2 paired-reads (in 1 unique pairings) successfully merged out of 43210 (in 14827 pairings) input.
4 paired-reads (in 2 unique pairings) successfully merged out of 35459 (in 9332 pairings) input.
0 paired-reads (in 0 unique pairings) successfully merged out of 40116 (in 9552 pairings) input.

> head(mergers[[1]])
[1] sequence  abundance forward   reverse   nmatch    nmismatch nindel    prefer    accept   
<0 rows> (or 0-length row.names)

> seqtab <- makeSequenceTable(mergers)
The sequences being tabled vary in length.

> dim(seqtab)
[1] 6 6

> table(nchar(getSequences(seqtab)))

277 284 288 294 304 
  1   1   2   1   1 

> taxa <- assignTaxonomy(seqtab.nochim, "~/Desktop/Sassoubre16S/unzipped/rdp_train_set_14.fa.gz")
> unname(head(taxa))
     [,1]       [,2] [,3] [,4] [,5] [,6]
[1,] "Bacteria" NA   NA   NA   NA   NA  
[2,] "Archaea"  NA   NA   NA   NA   NA  
[3,] "Bacteria" NA   NA   NA   NA   NA  
[4,] NA         NA   NA   NA   NA   NA  
[5,] NA         NA   NA   NA   NA   NA  
[6,] "Bacteria" NA   NA   NA   NA   NA  

I'm not sure what to try next?
Thank you!
Lou

**Comment by benjjneb** [comment] 2017-03-08 04:32
This is almost certainly due to trimming issues.

Two questions: What size is the amplicon you are sequencing? And what truncation lengths did you use?

The truncated reads must be long enough to span the amplicon (with 20 nts left over by default) in order for them to overlap and be merged.

**Comment by lmsroo** [comment] 2017-03-09 01:38
The sequences are for 16S V4V5 so ~410 bp. Are you asking about truncLen? If so, I chose 220 and 150 after looking at the plotQualityProfile but maybe I misunderstood what truncLen was trimming? Here is the code I used for filtering:
# Filter
for(i in seq_along(fnFs)) {
  fastqPairedFilter(c(fnFs[i], fnRs[i]), c(filtFs[i], filtRs[i]),
                    truncLen=c(220,150), 
                    maxN=0, maxEE=c(2,2), truncQ=2, rm.phix=FALSE,
                    compress=TRUE, verbose=TRUE)
}
Sorry if I'm totally off base and thanks for your patience!

**Comment by benjjneb** [comment] 2017-03-09 02:22
The issue is that you have truncated your reads too much for them to overlap. The amplicon is ~410nt, but if truncating at 220/150 you only have 370 total nts. So the reads aren't meeting in the middle.

You need to re-filter, and relax the truncation lengths. You should probably aim for something close to 450 total nts.

If this reduces the fraction of reads passing the filter too much (because of the lower-quality tails) feel free to raise `maxEE` as well. DADA2 is quite robust to lower quality sequence because of its error model.

ps: Unless you have a good reason, I would set `rm.phix=TRUE`, no need to keep artefactual sequences around!

**Comment by lmsroo** [comment] 2017-03-09 02:33
Thank you so much!! I'll try it again with the different truncation. What is the amplicon length of the data you provide for the tutorial?

**Comment by benjjneb** [comment] 2017-03-09 02:40
The tutorial data is essentially completely overlapping V4 reads, the amplicon is ~253 nts, basically the same as the read length, so we can trim entirely based on the quality profile.

This is a very common place people get tripped up though, we should think about improving the documentation on this point.

**Comment by lmsroo** [comment] 2017-03-09 02:45
Thanks! That makes more sense now.

**Closed** 2017-03-09 02:47 UTC
